"""Thin driver for the employment-services coverage pipeline.

Every rule lives in sql/. This file holds no business logic: it sequences the
SQL files, copies the mart into bi/exports/, re-emits that mart as
dashboard/data.js, and diffs out/ against the golden copies in expected/.

  python run.py            run the SQL end to end, then verify
  python run.py verify     golden diff only
  python run.py show       print centres per declared region
"""

import csv
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]

OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")
RESULT_CSV = os.path.join(OUT_DIR, "services_coverage.csv")
MART_CSV = os.path.join(OUT_DIR, "mart_services.csv")
BI_MART_CSV = os.path.join(HERE, "bi", "exports", "mart_services.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")

# Which mart columns are numeric in the JS literal. Plumbing for the emitter
# below, not a rule: the values themselves come straight from the mart.
JS_INT_COLUMNS = (
    "has_email", "has_web", "has_facebook", "has_twitter",
    "contact_channels", "region_centres",
)
JS_FLOAT_COLUMNS = ("latitude", "longitude", "region_share_pct")


def run_pipeline():
    import duckdb

    os.chdir(HERE)  # the SQL reads and writes paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)
    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            with open(os.path.join(HERE, "sql", name), "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
    finally:
        con.close()

    os.makedirs(os.path.dirname(BI_MART_CSV), exist_ok=True)
    shutil.copyfile(MART_CSV, BI_MART_CSV)
    print("copied mart to bi/exports/mart_services.csv")

    write_data_js()
    print("regenerated dashboard/data.js")
    print("")


def write_data_js():
    """Plumbing only: re-emit the mart rows as a JS array literal."""
    with open(MART_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    records = []
    for row in rows:
        record = {}
        for key, value in row.items():
            if value == "":
                record[key] = None
            elif key in JS_INT_COLUMNS:
                record[key] = int(value)
            elif key in JS_FLOAT_COLUMNS:
                record[key] = float(value)
            else:
                record[key] = value
        records.append("  " + json.dumps(record, sort_keys=False))
    header = (
        "// Generated by run.py from out/mart_services.csv. Do not edit.\n"
        "// One row per Nova Scotia Works centre. latitude and longitude are\n"
        "// already corrected for the source's reversed coordinate columns.\n"
    )
    body = "const DATA = [\n" + ",\n".join(records) + "\n];\n"
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + body)


def verify():
    names = sorted(n for n in os.listdir(EXPECTED_DIR) if n.endswith(".csv"))
    if not names:
        print("FAIL: expected/ holds no golden files to compare against")
        return 1
    for name in names:
        got_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(got_path):
            print("FAIL: out/%s is missing (run: python run.py)" % name)
            return 1
        with open(os.path.join(EXPECTED_DIR, name), "r", encoding="utf-8") as f:
            want = f.read().splitlines()
        with open(got_path, "r", encoding="utf-8") as f:
            got = f.read().splitlines()
        for i in range(max(len(want), len(got))):
            w = want[i] if i < len(want) else "<missing line>"
            g = got[i] if i < len(got) else "<extra line>"
            if w != g:
                print("FAIL: %s line %d" % (name, i + 1))
                print("  expected: " + w)
                print("  got:      " + g)
                return 1
        print("PASS: out/%s matches expected/%s (%d lines)"
              % (name, name, len(got)))
    return 0


def show():
    if not os.path.exists(RESULT_CSV):
        print("out/services_coverage.csv not found; run `python run.py` first")
        return 1
    with open(RESULT_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    summary = {r["measure"]: r["centres"] for r in rows if r["section"] == "summary"}
    regions = [r for r in rows if r["section"] == "region_coverage"]

    columns = [
        ("rank", "rank", "r"),
        ("region", "region", "l"),
        ("centres", "centres", "r"),
        ("towns", "towns", "r"),
        ("providers", "providers", "r"),
        ("share_pct", "share %", "r"),
    ]
    table = [[r[key] for key, _, _ in columns] for r in regions]
    widths = [len(label) for _, label, _ in columns]
    for line in table:
        for i, cell in enumerate(line):
            widths[i] = max(widths[i], len(cell))

    def fmt(cells):
        parts = []
        for i, cell in enumerate(cells):
            align = columns[i][2]
            parts.append(cell.ljust(widths[i]) if align == "l"
                         else cell.rjust(widths[i]))
        return "  ".join(parts)

    print("")
    print("Nova Scotia Works centres per declared region")
    print("")
    print(fmt([label for _, label, _ in columns]))
    print(fmt(["-" * w for w in widths]))
    for line in table:
        print(fmt(line))
    print("")
    print("%s centres, %s of %s declared regions covered, %s towns, %s FSAs, "
          "%s providers"
          % (summary.get("total_centres", "?"),
             summary.get("regions_with_centres", "?"),
             summary.get("declared_regions", "?"),
             summary.get("distinct_towns", "?"),
             summary.get("distinct_fsas", "?"),
             summary.get("distinct_providers", "?")))
    print("")
    return 0


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "run"
    if mode == "run":
        run_pipeline()
        sys.exit(verify())
    if mode == "verify":
        sys.exit(verify())
    if mode == "show":
        sys.exit(show())
    print(__doc__)
    sys.exit(2)


if __name__ == "__main__":
    main()
