"""Indexer: read the curated dataset, check it, and build the knowledge graph.

This is the step you run once. It reads data/materia.json, validates it, builds
the node-and-edge graph, and saves it to a single SQLite file (ff7graph.db) that
the query tool reads. It also writes web/data.js so the browser explorer shows
the same data without any server.

    python build_index.py

Standard library only: json and sqlite3.
"""

import json
import os
import sqlite3
import sys

from ff7_graph import build_graph
from validate import validate

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA_PATH = os.path.join(ROOT, "data", "materia.json")
DB_PATH = os.path.join(ROOT, "ff7graph.db")
WEB_DATA_PATH = os.path.join(ROOT, "web", "data.js")


def load_dataset(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def write_database(graph, db_path):
    nodes, edges = graph.to_records()
    if os.path.exists(db_path):
        os.remove(db_path)
    conn = sqlite3.connect(db_path)
    try:
        cur = conn.cursor()
        cur.execute("CREATE TABLE nodes (id TEXT PRIMARY KEY, type TEXT, label TEXT, attrs TEXT)")
        cur.execute("CREATE TABLE edges (id INTEGER PRIMARY KEY, src TEXT, rel TEXT, dst TEXT, attrs TEXT)")
        cur.executemany(
            "INSERT INTO nodes (id, type, label, attrs) VALUES (?, ?, ?, ?)",
            [(n["id"], n["type"], n["label"], json.dumps(n["attrs"])) for n in nodes],
        )
        cur.executemany(
            "INSERT INTO edges (src, rel, dst, attrs) VALUES (?, ?, ?, ?)",
            [(e["src"], e["rel"], e["dst"], json.dumps(e["attrs"])) for e in edges],
        )
        cur.execute("CREATE INDEX idx_edges_src ON edges (src)")
        cur.execute("CREATE INDEX idx_edges_dst ON edges (dst)")
        conn.commit()
    finally:
        conn.close()


def write_web_data(data, path):
    """Mirror the dataset into a JS file the browser can load with a script tag."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("// Generated by build_index.py from data/materia.json. Do not edit by hand.\n")
        handle.write("window.FF7_DATA = ")
        handle.write(payload)
        handle.write(";\n")


def main():
    print("Reading %s" % os.path.relpath(DATA_PATH, ROOT))
    data = load_dataset(DATA_PATH)

    errors = validate(data)
    if errors:
        print("\nThe dataset has problems, so nothing was built:\n")
        for message in errors:
            print("  - " + message)
        return 1

    graph = build_graph(data)
    write_database(graph, DB_PATH)
    write_web_data(data, WEB_DATA_PATH)

    counts = graph.counts()
    print("\nBuilt the graph and saved it to %s" % os.path.relpath(DB_PATH, ROOT))
    print("Wrote browser data to %s" % os.path.relpath(WEB_DATA_PATH, ROOT))
    print("\n  %d nodes" % counts["nodes"])
    for ntype in sorted(counts["nodes_by_type"]):
        print("      %-10s %d" % (ntype, counts["nodes_by_type"][ntype]))
    print("  %d edges" % counts["edges"])
    for rel in sorted(counts["edges_by_rel"]):
        print("      %-12s %d" % (rel, counts["edges_by_rel"][rel]))
    print("\nNext: python query.py stats")
    return 0


if __name__ == "__main__":
    sys.exit(main())
