"""Thin driver for the emergency department closure hours pipeline.

All analytical logic lives in sql/. This file only executes the SQL files in
order, copies the mart into bi/exports/, regenerates dashboard/data.js from the
mart, and diffs out/ against the golden copy in expected/.

  python run.py            run the pipeline, then verify against expected/
  python run.py verify     golden diff only
  python run.py show       print closure hours by zone as an aligned table
"""

import csv
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]

OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")
RESULT_CSV = os.path.join(OUT_DIR, "ed_closures.csv")
MART_CSV = os.path.join(OUT_DIR, "mart_ed_closures.csv")
BI_MART_CSV = os.path.join(HERE, "bi", "exports", "mart_ed_closures.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")


def run_pipeline():
    import duckdb

    os.chdir(HERE)  # the SQL files use paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)
    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            path = os.path.join(HERE, "sql", name)
            with open(path, "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
        print("")
        for (line,) in con.execute(
                "SELECT line FROM headline ORDER BY ord").fetchall():
            print(line)
        print("")
    finally:
        con.close()

    os.makedirs(os.path.dirname(BI_MART_CSV), exist_ok=True)
    shutil.copyfile(MART_CSV, BI_MART_CSV)
    print("copied mart to bi/exports/mart_ed_closures.csv")

    write_data_js()
    print("regenerated dashboard/data.js")


def write_data_js():
    """Plumbing only: re-emit the mart rows as a JS array literal. No figure is
    computed here; the dashboard derives every number it shows from these rows."""
    with open(MART_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    lines = []
    for r in rows:
        lines.append(
            '  {"fiscal_year": "%s", "fiscal_year_start": %s, "zone": "%s", '
            '"facility_type": "%s", "site": %s, "temporary_hours": %s, '
            '"scheduled_hours": %s, "total_hours": %s, "is_zero_closure": %s}'
            % (
                r["fiscal_year"],
                r["fiscal_year_start"],
                r["zone"],
                r["facility_type"],
                json_string(r["site"]),
                r["temporary_hours"],
                r["scheduled_hours"],
                r["total_hours"],
                r["is_zero_closure"],
            )
        )
    body = "const DATA = [\n" + ",\n".join(lines) + "\n];\n"
    header = (
        "// Generated by run.py from out/mart_ed_closures.csv. Do not edit.\n"
        "// One row per site and fiscal year: temporary, scheduled, and total\n"
        "// closure hours as reported by Nova Scotia Open Data.\n"
    )
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + body)


def json_string(value):
    """Quote a site name for the JS literal. Site names carry apostrophes and
    ampersands, so the quoting cannot be assumed away."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def verify():
    failures = 0
    checked = 0
    for name in sorted(os.listdir(EXPECTED_DIR)):
        exp_path = os.path.join(EXPECTED_DIR, name)
        got_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(got_path):
            print("FAIL: out/%s is missing (run: python run.py)" % name)
            return 1
        with open(exp_path, "r", encoding="utf-8") as f:
            exp = f.read().splitlines()
        with open(got_path, "r", encoding="utf-8") as f:
            got = f.read().splitlines()
        checked += 1
        for i in range(max(len(exp), len(got))):
            e = exp[i] if i < len(exp) else "<missing line>"
            g = got[i] if i < len(got) else "<missing line>"
            if e != g:
                print("FAIL: %s line %d" % (name, i + 1))
                print("  expected: " + e)
                print("  got:      " + g)
                failures += 1
                break
    if checked == 0:
        print("FAIL: expected/ holds no golden files to compare against")
        return 1
    if failures == 0:
        print("PASS: %d file(s) match expected/ row for row" % checked)
        return 0
    return 1


def show():
    if not os.path.exists(RESULT_CSV):
        run_pipeline()
    with open(RESULT_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    def table(title, columns, picked):
        widths = [len(c[1]) for c in columns]
        cells = []
        for r in picked:
            line = [r[c[0]] for c in columns]
            for i, v in enumerate(line):
                widths[i] = max(widths[i], len(v))
            cells.append(line)

        def fmt(values):
            parts = []
            for i, v in enumerate(values):
                parts.append(v.ljust(widths[i]) if i == 0 else v.rjust(widths[i]))
            return "  ".join(parts).rstrip()

        print(title)
        print("")
        print(fmt([c[1] for c in columns]))
        print(fmt(["-" * w for w in widths]))
        for line in cells:
            print(fmt(line))
        print("")

    table(
        "Nova Scotia emergency department closure hours, provincial summary",
        [("measure", "measure"), ("site_years", "count"),
         ("total_hours", "total hours"), ("temporary_hours", "temporary"),
         ("scheduled_hours", "scheduled"),
         ("temporary_share_pct", "temp share %")],
        [r for r in rows if r["section"] == "summary"],
    )
    table(
        "Closure hours by zone, 2012-13 to 2023-24",
        [("zone", "zone"), ("site_years", "site-years"),
         ("zero_site_years", "zero years"), ("total_hours", "total hours"),
         ("temporary_hours", "temporary"), ("scheduled_hours", "scheduled"),
         ("temporary_share_pct", "temp share %")],
        [r for r in rows if r["section"] == "zone_totals"],
    )
    return 0


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "run"
    if mode == "verify":
        sys.exit(verify())
    if mode == "show":
        sys.exit(show())
    if mode == "run":
        run_pipeline()
        sys.exit(verify())
    print("usage: python run.py [verify|show]")
    sys.exit(2)


if __name__ == "__main__":
    main()
