"""Thin driver for the public-tree inventory pipeline.

All analytical logic lives in sql/. This file only executes the SQL files in
order, copies the mart where the BI tools expect it, regenerates the browser
dashboard's data.js from the exported aggregates, and diffs the generated
output against the golden copies in expected/.

  python run.py            run the pipeline, then verify against expected/
  python run.py verify     golden diff only
  python run.py show       print the inventory summary as aligned tables
"""

import csv
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]

OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")
MART_CSV = os.path.join(OUT_DIR, "mart_trees.csv")
BI_MART_CSV = os.path.join(HERE, "bi", "exports", "mart_trees.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")


def run_pipeline():
    import duckdb

    os.chdir(HERE)  # the SQL files use paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)
    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            with open(os.path.join(HERE, "sql", name), "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
        print("")
        for (line,) in con.execute("SELECT line FROM headline ORDER BY ord").fetchall():
            print(line)
        print("")
    finally:
        con.close()

    os.makedirs(os.path.dirname(BI_MART_CSV), exist_ok=True)
    shutil.copyfile(MART_CSV, BI_MART_CSV)
    print("copied mart to bi/exports/mart_trees.csv")

    write_data_js()
    print("regenerated dashboard/data.js")


def read_csv_rows(name):
    with open(os.path.join(OUT_DIR, name), "r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_data_js():
    """Plumbing only: re-emit the exported aggregates as a JS object literal so
    the dashboard opens from disk with no server and no fetch. The dashboard
    re-derives its headline figures from these rows; see spec.md."""
    summary = {r["metric"]: r["value"] for r in read_csv_rows("summary.csv")}

    species = [
        {
            "rank": int(r["species_rank"]),
            "common": r["species_common"],
            "scientific": r["species_scientific"],
            "count": int(r["tree_count"]),
            "share": float(r["share_of_all_pct"]),
        }
        for r in read_csv_rows("species_ranking.csv")
    ]
    dbh = [
        {"cls": r["dbh_class"], "count": int(r["tree_count"]), "share": float(r["share_pct"])}
        for r in read_csv_rows("dbh_class_distribution.csv")
    ]
    wires = [
        {"label": r["wires"], "count": int(r["tree_count"]), "share": float(r["share_pct"])}
        for r in read_csv_rows("wires_distribution.csv")
    ]
    setting = [
        {"label": r["setting"], "count": int(r["tree_count"]), "share": float(r["share_pct"])}
        for r in read_csv_rows("setting_distribution.csv")
    ]

    payload = {
        "summary": summary,
        "species": species,
        "dbh": dbh,
        "wires": wires,
        "setting": setting,
    }
    header = (
        "// Generated by run.py from the exported aggregates in out/. Do not edit.\n"
        "// The dashboard re-derives its headline figures from these rows; the\n"
        "// derived totals must equal expected/summary.csv (see spec.md).\n"
    )
    os.makedirs(os.path.dirname(DATA_JS), exist_ok=True)
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + "const DATA = " + json.dumps(payload, indent=2) + ";\n")


def verify():
    if not os.path.isdir(EXPECTED_DIR):
        print("FAIL: expected/ does not exist")
        return 1
    golden = sorted(n for n in os.listdir(EXPECTED_DIR) if n.endswith(".csv"))
    if not golden:
        print("FAIL: expected/ holds no golden files to compare against")
        return 1

    failures = 0
    for name in golden:
        got_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(got_path):
            print("FAIL: out/%s is missing (run: python run.py)" % name)
            return 1
        with open(os.path.join(EXPECTED_DIR, name), "r", encoding="utf-8") as f:
            exp = f.read().splitlines()
        with open(got_path, "r", encoding="utf-8") as f:
            got = f.read().splitlines()
        for i in range(max(len(exp), len(got))):
            e = exp[i] if i < len(exp) else "<missing line>"
            g = got[i] if i < len(got) else "<missing line>"
            if e != g:
                print("FAIL: %s line %d" % (name, i + 1))
                print("  expected: " + e)
                print("  got:      " + g)
                failures += 1
                break

    if failures == 0:
        print("PASS: %d golden file(s) match expected/ row for row" % len(golden))
        return 0
    return 1


def print_table(columns, rows):
    """Aligned plain-ASCII table (Windows cp1252 safe). Numeric columns are
    right-aligned. Display only: it projects columns the SQL already produced."""
    cells = [["" if v is None else str(v) for v in row] for row in rows]

    def is_number(text):
        if text == "":
            return True
        try:
            float(text)
            return True
        except ValueError:
            return False

    numeric = [all(is_number(row[i]) for row in cells) for i in range(len(columns))]
    widths = [len(columns[i]) for i in range(len(columns))]
    for row in cells:
        for i, text in enumerate(row):
            widths[i] = max(widths[i], len(text))

    def line(values):
        parts = []
        for i, text in enumerate(values):
            parts.append(text.rjust(widths[i]) if numeric[i] else text.ljust(widths[i]))
        return "  ".join(parts)

    print(line(columns))
    print("  ".join("-" * w for w in widths))
    for row in cells:
        print(line(row))


def show():
    if not os.path.exists(os.path.join(OUT_DIR, "summary.csv")):
        run_pipeline()

    summary = {r["metric"]: r["value"] for r in read_csv_rows("summary.csv")}
    print("\nHRM public-tree inventory: headline\n")
    print_table(
        ["metric", "value"],
        [(r["metric"], r["value"]) for r in read_csv_rows("summary.csv")],
    )

    print("\nTop 15 species by tree count:\n")
    species = read_csv_rows("species_ranking.csv")[:15]
    print_table(
        ["rank", "species_common", "species_scientific", "tree_count", "share_of_all_pct"],
        [(r["species_rank"], r["species_common"], r["species_scientific"],
          r["tree_count"], r["share_of_all_pct"]) for r in species],
    )

    print("\nDBH size-class distribution:\n")
    print_table(
        ["dbh_class", "tree_count", "share_pct"],
        [(r["dbh_class"], r["tree_count"], r["share_pct"])
         for r in read_csv_rows("dbh_class_distribution.csv")],
    )

    print("\nWires-present distribution:\n")
    print_table(
        ["wires", "tree_count", "share_pct"],
        [(r["wires"], r["tree_count"], r["share_pct"])
         for r in read_csv_rows("wires_distribution.csv")],
    )

    print("\nGeneral-location distribution:\n")
    print_table(
        ["setting", "tree_count", "share_pct"],
        [(r["setting"], r["tree_count"], r["share_pct"])
         for r in read_csv_rows("setting_distribution.csv")],
    )
    print("")
    return 0


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "run"
    if mode == "verify":
        sys.exit(verify())
    if mode == "show":
        sys.exit(show())
    if mode == "run":
        run_pipeline()
        sys.exit(verify())
    print("usage: python run.py [verify|show]")
    sys.exit(2)


if __name__ == "__main__":
    main()
