"""Thin driver for the property tax burden index pipeline.

All analytical logic lives in sql/, executed in filename order. This file
only sequences the scripts, regenerates dashboard/data.js from the mart,
compares out/ against expected/, and prints tables. It holds no business
logic.

Usage:
    python run.py            run the SQL end to end, rebuild data.js, verify
    python run.py verify     golden diff only
    python run.py show       print the ranked latest-year spread table
"""

import csv
import json
import os
import sys
from pathlib import Path

import duckdb

HERE = Path(__file__).resolve().parent
SQL_DIR = HERE / "sql"
OUT_CSV = HERE / "out" / "tax_burden_index.csv"
EXPECTED_CSV = HERE / "expected" / "tax_burden_index.csv"
MART_CSV = HERE / "bi" / "exports" / "mart_tax_burden.csv"
DATA_JS = HERE / "dashboard" / "data.js"


def run_sql():
    (HERE / "out").mkdir(exist_ok=True)
    con = duckdb.connect()
    for script in sorted(SQL_DIR.glob("*.sql")):
        print(f"running sql/{script.name}")
        con.execute(script.read_text(encoding="utf-8"))
    con.close()


def read_mart_rows():
    with open(MART_CSV, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_data_js():
    rows = []
    for r in read_mart_rows():
        rows.append({
            "area": r["area"],
            "area_type": r["area_type"],
            "year_label": r["year_label"],
            "year_start": int(r["year_start"]),
            "residential_rate": float(r["residential_rate"]),
            "commercial_rate": float(r["commercial_rate"]),
            "spread": float(r["spread"]),
            "rank_in_year": int(r["rank_in_year"]),
            "yoy_spread_change": None if r["yoy_spread_change"] == "" else float(r["yoy_spread_change"]),
            "is_outlier": r["is_outlier"] == "true",
        })
    body = json.dumps(rows, indent=2)
    DATA_JS.write_text(
        "// Generated by run.py from bi/exports/mart_tax_burden.csv. Do not edit.\n"
        "const DATA = " + body + ";\n",
        encoding="utf-8",
    )
    print(f"wrote dashboard/data.js ({len(rows)} rows)")


def verify():
    if not OUT_CSV.exists():
        print("out/tax_burden_index.csv not found; run `python run.py` first")
        return 1
    out_lines = OUT_CSV.read_text(encoding="utf-8").splitlines()
    exp_lines = EXPECTED_CSV.read_text(encoding="utf-8").splitlines()
    for i in range(max(len(out_lines), len(exp_lines))):
        got = out_lines[i] if i < len(out_lines) else "<missing line>"
        want = exp_lines[i] if i < len(exp_lines) else "<missing line>"
        if got != want:
            print(f"FAIL at line {i + 1}")
            print(f"  expected: {want}")
            print(f"  got:      {got}")
            return 1
    print(f"PASS ({len(out_lines) - 1} rows match expected/tax_burden_index.csv)")
    return 0


def show():
    if not OUT_CSV.exists():
        print("out/tax_burden_index.csv not found; run `python run.py` first")
        return 1
    with open(OUT_CSV, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    latest = max(r["year_start"] for r in rows)
    rows = [r for r in rows if r["year_start"] == latest]
    cols = ["rank_in_year", "area", "area_type", "residential_rate",
            "commercial_rate", "spread", "yoy_spread_change", "is_outlier"]
    right_align = {"rank_in_year", "residential_rate", "commercial_rate",
                   "spread", "yoy_spread_change"}
    header = {c: c for c in cols}
    widths = {c: max(len(r[c]) for r in [header] + rows) for c in cols}
    print(f"Ranked residential vs commercial spread, fiscal {rows[0]['year_label']}")
    print()
    for r in [header] + rows:
        cells = []
        for c in cols:
            cells.append(r[c].rjust(widths[c]) if c in right_align else r[c].ljust(widths[c]))
        print("  ".join(cells).rstrip())
    return 0


def main():
    os.chdir(HERE)
    cmd = sys.argv[1] if len(sys.argv) > 1 else "run"
    if cmd == "run":
        run_sql()
        write_data_js()
        sys.exit(verify())
    elif cmd == "verify":
        sys.exit(verify())
    elif cmd == "show":
        sys.exit(show())
    else:
        print(__doc__)
        sys.exit(2)


if __name__ == "__main__":
    main()
