"""Thin driver for the traffic collision safety map pipeline.

All analytical logic lives in sql/. This file only executes the SQL files in
order (00 to 99), which do the loading, cleaning, aggregating, and exporting,
then it copies the frozen mart into bi/exports/, regenerates dashboard/data.js
from the SQL outputs, and diffs the generated goldens against expected/.

  python run.py            run the SQL end to end, then verify out vs expected
  python run.py verify     re-run only the out-vs-expected diff
  python run.py show       print the per-year and month-by-hour results as tables
"""

import csv
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]

OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")
BY_YEAR_CSV = os.path.join(OUT_DIR, "collisions_by_year.csv")
MONTH_HOUR_CSV = os.path.join(OUT_DIR, "collisions_month_hour.csv")
META_CSV = os.path.join(OUT_DIR, "meta.csv")
MART_CSV = os.path.join(OUT_DIR, "mart_collisions.csv")
BI_MART_CSV = os.path.join(HERE, "bi", "exports", "mart_collisions.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")


def run_pipeline():
    import duckdb

    os.chdir(HERE)  # SQL files use paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)
    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            path = os.path.join(HERE, "sql", name)
            with open(path, "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
        print("")
        for (line,) in con.execute(
                "SELECT line FROM headline ORDER BY ord").fetchall():
            print(line)
        print("")
    finally:
        con.close()

    os.makedirs(os.path.dirname(BI_MART_CSV), exist_ok=True)
    shutil.copyfile(MART_CSV, BI_MART_CSV)
    print("copied mart to bi/exports/mart_collisions.csv")

    write_data_js()
    print("regenerated dashboard/data.js")


def read_csv_rows(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        return list(csv.reader(f))


def js_array(rows, header, int_cols):
    """Plumbing only: turn CSV rows into a JS array-of-objects literal. Numeric
    columns are emitted bare; everything else is quoted. No values are computed
    here, the SQL already produced them."""
    out = []
    for r in rows:
        parts = []
        for i, col in enumerate(header):
            val = r[i]
            if col in int_cols:
                parts.append('"%s": %s' % (col, val if val != "" else "null"))
            else:
                parts.append('"%s": %s' % (col, _num_or_str(val)))
        out.append("  {" + ", ".join(parts) + "}")
    return "[\n" + ",\n".join(out) + "\n]"


def _num_or_str(val):
    if val == "":
        return "null"
    try:
        float(val)
        return val
    except ValueError:
        return '"' + val.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_data_js():
    """Re-emit the SQL outputs as JS literals for the file:// dashboard. Pure
    plumbing: the dashboard re-derives its headline figures from these arrays."""
    by_year = read_csv_rows(BY_YEAR_CSV)
    month_hour = read_csv_rows(MONTH_HOUR_CSV)
    meta = read_csv_rows(META_CSV)

    by_year_h, by_year_rows = by_year[0], by_year[1:]
    mh_h, mh_rows = month_hour[0], month_hour[1:]
    meta_h, meta_row = meta[0], meta[1]

    meta_obj = "{" + ", ".join(
        '"%s": %s' % (col, _num_or_str(meta_row[i]))
        for i, col in enumerate(meta_h)) + "}"

    by_year_int = set(by_year_h)  # every by-year column is numeric
    mh_int = set(mh_h)            # every month-hour column is numeric

    body = (
        "// Generated by run.py from the SQL outputs in out/. Do not edit.\n"
        "// META: the pull-date constant and the latest full year.\n"
        "// BY_YEAR: one row per year, collision count, factor counts and shares.\n"
        "// MONTH_HOUR: one row per hour of day, twelve month columns of counts.\n"
        "const META = " + meta_obj + ";\n"
        "const BY_YEAR = " + js_array(by_year_rows, by_year_h, by_year_int) + ";\n"
        "const MONTH_HOUR = " + js_array(mh_rows, mh_h, mh_int) + ";\n"
    )
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)


def verify():
    failures = 0
    checked = 0
    for name in sorted(os.listdir(EXPECTED_DIR)):
        if not name.endswith(".csv"):
            continue
        exp_path = os.path.join(EXPECTED_DIR, name)
        got_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(got_path):
            print("FAIL: out/%s is missing (run: python run.py)" % name)
            return 1
        with open(exp_path, "r", encoding="utf-8") as f:
            exp = f.read().splitlines()
        with open(got_path, "r", encoding="utf-8") as f:
            got = f.read().splitlines()
        checked += 1
        row_failed = False
        for i in range(max(len(exp), len(got))):
            e = exp[i] if i < len(exp) else "<missing line>"
            g = got[i] if i < len(got) else "<missing line>"
            if e != g:
                print("FAIL: %s line %d" % (name, i + 1))
                print("  expected: " + e)
                print("  got:      " + g)
                failures += 1
                row_failed = True
                break
        if not row_failed:
            print("PASS: %s matches expected/ (%d rows)" % (name, len(got) - 1))
    if checked == 0:
        print("FAIL: expected/ holds no golden files to compare against")
        return 1
    if failures == 0:
        print("PASS: %d golden file(s) match expected/ row for row" % checked)
        return 0
    return 1


def print_table(header, rows):
    widths = [len(h) for h in header]
    for r in rows:
        for i, cell in enumerate(r):
            widths[i] = max(widths[i], len(cell))

    def fmt(cells):
        parts = []
        for i, cell in enumerate(cells):
            parts.append(cell.rjust(widths[i]) if i > 0 else cell.ljust(widths[i]))
        return "  ".join(parts)

    print(fmt(header))
    print("  ".join("-" * w for w in widths))
    for r in rows:
        print(fmt(r))


def show():
    if not os.path.exists(BY_YEAR_CSV) or not os.path.exists(MONTH_HOUR_CSV):
        run_pipeline()

    by_year = read_csv_rows(BY_YEAR_CSV)
    month_hour = read_csv_rows(MONTH_HOUR_CSV)

    print("\nCollisions by year, with each contributing factor's share (percent):\n")
    print_table(by_year[0], by_year[1:])

    print("\nMonth-by-hour collision counts (hour of day down, month across):\n")
    print_table(month_hour[0], month_hour[1:])
    print("")
    return 0


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "run"
    if mode == "verify":
        sys.exit(verify())
    if mode == "show":
        sys.exit(show())
    if mode == "run":
        run_pipeline()
        sys.exit(verify())
    print("usage: python run.py [verify|show]")
    sys.exit(2)


if __name__ == "__main__":
    main()
