/* Reads the DATA array from data.js (generated by run.py from the SQL mart)
   and re-derives every figure on the page. Nothing is hardcoded: if the SQL
   output changes, this page changes with it.

   The derivation functions are pure and kept at the top so they can be run
   headlessly (node) against data.js to prove the headline matches the golden
   output. */

function round4(x) {
  return Math.round(x * 10000) / 10000;
}

function latestYear(rows) {
  return rows.reduce(function (m, r) { return Math.max(m, r.year_start); }, -Infinity);
}

/* Latest-year rows, widest spread first; area name then area type break ties,
   matching the SQL export order. */
function latestRows(rows) {
  var y = latestYear(rows);
  return rows
    .filter(function (r) { return r.year_start === y; })
    .slice()
    .sort(function (a, b) {
      if (b.spread !== a.spread) { return b.spread - a.spread; }
      if (a.area !== b.area) { return a.area < b.area ? -1 : 1; }
      return a.area_type < b.area_type ? -1 : a.area_type > b.area_type ? 1 : 0;
    });
}

function widestSpread(rows) {
  return latestRows(rows)[0];
}

/* Median of latest-year spreads: sort ascending, average the two middle
   values when the count is even. Same rule as SQL's median(). */
function medianSpread(rows) {
  var s = latestRows(rows).map(function (r) { return r.spread; }).sort(function (a, b) { return a - b; });
  var n = s.length;
  var mid = n % 2 === 1 ? s[(n - 1) / 2] : (s[n / 2 - 1] + s[n / 2]) / 2;
  return round4(mid);
}

function outlierRows(rows) {
  return latestRows(rows).filter(function (r) { return r.is_outlier; });
}

/* One municipality's rows in year order. A municipality is (area, area_type):
   six names exist as both a Town and a Rural Municipality. */
function seriesFor(rows, area, areaType) {
  return rows
    .filter(function (r) { return r.area === area && r.area_type === areaType; })
    .slice()
    .sort(function (a, b) { return a.year_start - b.year_start; });
}

function fmt(x) {
  return x.toFixed(4);
}

function fmtSigned(x) {
  return (x >= 0 ? "+" : "") + x.toFixed(4);
}

/* ---- rendering ---------------------------------------------------------- */

function renderKpis(rows) {
  var top = widestSpread(rows);
  var latest = latestRows(rows);
  var flagged = outlierRows(rows);

  document.getElementById("latest-year-label").textContent = top.year_label;
  document.getElementById("kpi-widest-value").textContent = fmt(top.spread);
  document.getElementById("kpi-widest-area").textContent =
    top.area + " (" + top.area_type + "), per $100 assessed";
  document.getElementById("kpi-median-value").textContent = fmt(medianSpread(rows));
  document.getElementById("kpi-median-detail").textContent =
    "across " + latest.length + " municipalities";
  document.getElementById("kpi-outlier-count").textContent = String(flagged.length);
}

function renderRanking(rows) {
  var latest = latestRows(rows);
  var maxSpread = latest[0].spread;
  var list = document.getElementById("rank-list");
  list.textContent = "";

  latest.forEach(function (r) {
    var row = document.createElement("div");
    row.className = "rank-row";

    var num = document.createElement("div");
    num.className = "rank-num";
    num.textContent = String(r.rank_in_year);

    var name = document.createElement("div");
    name.className = "rank-name";
    name.textContent = r.area;
    var type = document.createElement("span");
    type.className = "rank-type";
    type.textContent = r.area_type;
    name.appendChild(type);

    var track = document.createElement("div");
    track.className = "rank-bar-track";
    var bar = document.createElement("div");
    bar.className = "rank-bar";
    bar.style.width = (Math.max(r.spread, 0) / maxSpread * 100).toFixed(2) + "%";
    track.appendChild(bar);

    var value = document.createElement("div");
    value.className = "rank-value";
    value.textContent = fmt(r.spread);

    var flag = document.createElement("div");
    if (r.is_outlier) {
      flag.className = "outlier-badge";
      flag.textContent = "Outlier";
    }

    row.appendChild(num);
    row.appendChild(name);
    row.appendChild(track);
    row.appendChild(value);
    row.appendChild(flag);
    list.appendChild(row);
  });
}

function renderTrend(rows, area, areaType) {
  var series = seriesFor(rows, area, areaType);
  var svg = document.getElementById("trend-chart");
  svg.textContent = "";

  var W = 680, H = 260, padL = 56, padR = 24, padT = 22, padB = 40;
  var spreads = series.map(function (r) { return r.spread; });
  var lo = Math.min.apply(null, spreads);
  var hi = Math.max.apply(null, spreads);
  if (hi === lo) { hi += 0.1; lo -= 0.1; }
  var y0 = series[0].year_start;
  var y1 = series[series.length - 1].year_start;
  var xSpan = Math.max(y1 - y0, 1);

  function px(year) { return padL + (year - y0) / xSpan * (W - padL - padR); }
  function py(v) { return padT + (hi - v) / (hi - lo) * (H - padT - padB); }

  var NS = "http://www.w3.org/2000/svg";
  var ink = "#16324f";

  [lo, (lo + hi) / 2, hi].forEach(function (v) {
    var line = document.createElementNS(NS, "line");
    line.setAttribute("x1", padL); line.setAttribute("x2", W - padR);
    line.setAttribute("y1", py(v)); line.setAttribute("y2", py(v));
    line.setAttribute("stroke", ink); line.setAttribute("stroke-opacity", "0.12");
    svg.appendChild(line);
    var label = document.createElementNS(NS, "text");
    label.setAttribute("x", padL - 10); label.setAttribute("y", py(v) + 4);
    label.setAttribute("text-anchor", "end");
    label.setAttribute("font-size", "11");
    label.setAttribute("font-family", "Verdana, Geneva, sans-serif");
    label.setAttribute("fill", ink); label.setAttribute("fill-opacity", "0.55");
    label.textContent = round4(v).toFixed(2);
    svg.appendChild(label);
  });

  [series[0], series[series.length - 1]].forEach(function (r) {
    var label = document.createElementNS(NS, "text");
    label.setAttribute("x", px(r.year_start)); label.setAttribute("y", H - 12);
    label.setAttribute("text-anchor", "middle");
    label.setAttribute("font-size", "11");
    label.setAttribute("font-family", "Verdana, Geneva, sans-serif");
    label.setAttribute("fill", ink); label.setAttribute("fill-opacity", "0.55");
    label.textContent = r.year_label;
    svg.appendChild(label);
  });

  var points = series.map(function (r) {
    return px(r.year_start).toFixed(1) + "," + py(r.spread).toFixed(1);
  }).join(" ");
  var poly = document.createElementNS(NS, "polyline");
  poly.setAttribute("points", points);
  poly.setAttribute("fill", "none");
  poly.setAttribute("stroke", ink);
  poly.setAttribute("stroke-width", "2.5");
  svg.appendChild(poly);

  series.forEach(function (r) {
    var dot = document.createElementNS(NS, "circle");
    dot.setAttribute("cx", px(r.year_start));
    dot.setAttribute("cy", py(r.spread));
    dot.setAttribute("r", "4");
    dot.setAttribute("fill", ink);
    svg.appendChild(dot);
  });

  var first = series[0];
  var last = series[series.length - 1];
  var text = area + " (" + areaType + "): spread " + fmt(first.spread) + " in " + first.year_label +
    ", " + fmt(last.spread) + " in " + last.year_label + ".";
  if (last.yoy_spread_change !== null && last.yoy_spread_change !== undefined) {
    text += " Latest year-over-year change: " + fmtSigned(last.yoy_spread_change) + ".";
  }
  document.getElementById("trend-summary").textContent = text;
}

function init() {
  renderKpis(DATA);
  renderRanking(DATA);

  var picker = document.getElementById("muni-picker");
  var latest = latestRows(DATA);
  latest.forEach(function (r, i) {
    var opt = document.createElement("option");
    opt.value = String(i);
    opt.textContent = r.area + " (" + r.area_type + ")";
    picker.appendChild(opt);
  });
  picker.value = "0";
  picker.addEventListener("change", function () {
    var r = latest[Number(picker.value)];
    renderTrend(DATA, r.area, r.area_type);
  });
  renderTrend(DATA, latest[0].area, latest[0].area_type);
}

if (typeof document !== "undefined") {
  document.addEventListener("DOMContentLoaded", init);
}

/* Headless hook for the verification run; ignored by the browser. */
if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    latestYear: latestYear,
    latestRows: latestRows,
    widestSpread: widestSpread,
    medianSpread: medianSpread,
    outlierRows: outlierRows,
    seriesFor: seriesFor
  };
}
