"""Thin driver for the capital investment map pipeline.

All analytical logic lives in sql/. This file only executes the SQL files in
order, copies the frozen mart into bi/exports/, regenerates dashboard/data.js
from that mart, and diffs the generated output against the golden copies in
expected/.

  python run.py            run the pipeline, then verify against expected/
  python run.py verify     golden diff only
  python run.py show       print the category ranking and asset-type counts
"""

import csv
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]

OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")
MART_CSV = os.path.join(OUT_DIR, "mart_capital.csv")
RANKING_CSV = os.path.join(OUT_DIR, "category_ranking.csv")
ASSET_CSV = os.path.join(OUT_DIR, "counts_by_asset_type.csv")
BI_MART_CSV = os.path.join(HERE, "bi", "exports", "mart_capital.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")


def run_pipeline():
    import duckdb

    os.chdir(HERE)  # SQL files use paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)
    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            path = os.path.join(HERE, "sql", name)
            with open(path, "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
        print("")
        for (line,) in con.execute(
                "SELECT line FROM headline ORDER BY ord").fetchall():
            print(line)
        print("")
    finally:
        con.close()

    os.makedirs(os.path.dirname(BI_MART_CSV), exist_ok=True)
    shutil.copyfile(MART_CSV, BI_MART_CSV)
    print("copied mart to bi/exports/mart_capital.csv")

    write_data_js()
    print("regenerated dashboard/data.js")


def write_data_js():
    """Plumbing only: re-emit the mart columns the dashboard needs as a JS array.
    year is an integer and lat/lon are numbers; the text columns are JSON-escaped
    so a comma, quote, or accented character in a description cannot break the
    file. The dashboard re-derives every headline figure from this array."""
    with open(MART_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    lines = []
    for r in rows:
        obj = {
            "proj_no": r["proj_no"],
            "proj_name": r["proj_name"],
            "loc_desc": r["loc_desc"],
            "category_norm": r["category_norm"],
            "asset_type": r["asset_type"],
            "year": int(r["year"]),
            "lat": float(r["lat"]),
            "lon": float(r["lon"]),
        }
        lines.append("  " + json.dumps(obj, ensure_ascii=False))
    body = "const DATA = [\n" + ",\n".join(lines) + "\n];\n"
    header = (
        "// Generated by run.py from bi/exports/mart_capital.csv. Do not edit.\n"
        "// One row per capital-project record: category, asset type, budget\n"
        "// year, and the WGS84 point. Every figure on the page derives from it.\n"
    )
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + body)


def verify():
    failures = 0
    checked = 0
    for name in sorted(os.listdir(EXPECTED_DIR)):
        exp_path = os.path.join(EXPECTED_DIR, name)
        got_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(got_path):
            print("FAIL: out/%s is missing (run: python run.py)" % name)
            return 1
        with open(exp_path, "r", encoding="utf-8") as f:
            exp = f.read().splitlines()
        with open(got_path, "r", encoding="utf-8") as f:
            got = f.read().splitlines()
        checked += 1
        for i in range(max(len(exp), len(got))):
            e = exp[i] if i < len(exp) else "<missing line>"
            g = got[i] if i < len(got) else "<missing line>"
            if e != g:
                print("FAIL: %s line %d" % (name, i + 1))
                print("  expected: " + e)
                print("  got:      " + g)
                failures += 1
                break
    if checked == 0:
        print("FAIL: expected/ holds no golden files to compare against")
        return 1
    if failures == 0:
        print("PASS: %d file(s) match expected/ row for row" % checked)
        return 0
    return 1


def print_table(header, rows):
    """Aligned plain-ASCII table. Numeric columns right-align. No box-drawing
    characters, so it prints cleanly on the default Windows code page."""
    cells = [[("" if c is None else str(c)) for c in r] for r in rows]

    def is_num(t):
        if t == "":
            return True
        try:
            float(t)
            return True
        except ValueError:
            return False

    numeric = [all(is_num(r[i]) for r in cells) for i in range(len(header))]
    widths = [len(h) for h in header]
    for r in cells:
        for i, t in enumerate(r):
            widths[i] = max(widths[i], len(t))

    def line(vals):
        return "  ".join(
            (t.rjust(widths[i]) if numeric[i] else t.ljust(widths[i]))
            for i, t in enumerate(vals))

    print(line(header))
    print("  ".join("-" * w for w in widths))
    for r in cells:
        print(line(r))


def read_csv_rows(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.reader(f))
    return rows[0], rows[1:]


def show():
    rank_src = RANKING_CSV if os.path.exists(RANKING_CSV) \
        else os.path.join(EXPECTED_DIR, "category_ranking.csv")
    asset_src = ASSET_CSV if os.path.exists(ASSET_CSV) \
        else os.path.join(EXPECTED_DIR, "counts_by_asset_type.csv")
    if not os.path.exists(rank_src):
        print("Nothing to show yet. Run: python run.py")
        return 1

    print("Capital projects by category (largest first)")
    print("")
    header, rows = read_csv_rows(rank_src)
    print_table(header, rows)

    print("")
    print("Capital projects by asset type")
    print("")
    header, rows = read_csv_rows(asset_src)
    print_table(header, rows)
    print("")
    return 0


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "run"
    if mode == "verify":
        sys.exit(verify())
    if mode == "show":
        sys.exit(show())
    if mode == "run":
        run_pipeline()
        sys.exit(verify())
    print("usage: python run.py [verify|show]")
    sys.exit(2)


if __name__ == "__main__":
    main()
