"""Thin driver for the building permit pulse pipeline.

This file holds no analytical logic. It executes the SQL files in order (00 to
99), which do all of the loading, transforming, aggregating, and exporting, then
it copies the frozen mart to bi/exports, regenerates the browser dashboard's
data.js from the SQL output, and diffs the goldens against expected/.

Usage:
    python run.py            run the SQL end to end, then verify out vs expected
    python run.py verify     re-run only the out-vs-expected diff
    python run.py show       print the results as aligned tables in the terminal
"""

import csv
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SQL_DIR = os.path.join(HERE, "sql")
OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")

MART_OUT = os.path.join(OUT_DIR, "mart_permits.csv")
MART_BI = os.path.join(HERE, "bi", "exports", "mart_permits.csv")
YEAR_TYPE_OUT = os.path.join(OUT_DIR, "permits_by_year_worktype.csv")
DISTRICT_OUT = os.path.join(OUT_DIR, "district_units_running_total.csv")
COMMUNITY_OUT = os.path.join(OUT_DIR, "permits_by_community.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")

PULL_DATE = "2026-07-09"

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]


def run_pipeline():
    """Run the SQL files in order, print the headline, then refresh the exports
    the BI tools and the dashboard read."""
    import duckdb

    os.chdir(HERE)  # the SQL files use paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)

    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            with open(os.path.join(SQL_DIR, name), "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
        print("")
        for (line,) in con.execute("SELECT line FROM headline ORDER BY ord").fetchall():
            print(line)
        print("")
    finally:
        con.close()

    os.makedirs(os.path.dirname(MART_BI), exist_ok=True)
    shutil.copyfile(MART_OUT, MART_BI)
    print("copied mart to bi/exports/mart_permits.csv")

    write_data_js()
    print("regenerated dashboard/data.js")


def _read_csv(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_data_js():
    """Plumbing only: re-emit three SQL outputs as JS array literals so the
    dashboard opens under file:// with no fetch. The dashboard re-derives its
    headline from these rows; it hardcodes nothing."""
    by_year_type = [
        {
            "year": int(r["issue_year"]),
            "work_type": r["work_type"],
            "permits": int(r["permit_count"]),
            "value": float(r["total_project_value"]),
            "net_new_units": int(r["total_net_new_units"]),
        }
        for r in _read_csv(YEAR_TYPE_OUT)
    ]
    district_run = [
        {
            "district": r["district"],
            "year": int(r["issue_year"]),
            "net_new_units": int(r["net_new_units"]),
            "cumulative": int(r["cumulative_net_new_units"]),
        }
        for r in _read_csv(DISTRICT_OUT)
    ]
    by_community = [
        {
            "community": r["community"],
            "permits": int(r["permit_count"]),
            "value": float(r["total_project_value"]),
            "net_new_units": int(r["total_net_new_units"]),
        }
        for r in _read_csv(COMMUNITY_OUT)
    ]

    def block(name, rows):
        body = ",\n".join("  " + json.dumps(r) for r in rows)
        return "const " + name + " = [\n" + body + "\n];\n"

    header = (
        "// Generated by run.py from the SQL output in out/. Do not edit.\n"
        "// The dashboard re-derives every headline figure from these rows.\n"
        'const PULL_DATE = "' + PULL_DATE + '";\n'
    )
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write(block("BY_YEAR_TYPE", by_year_type))
        f.write(block("DISTRICT_RUN", district_run))
        f.write(block("BY_COMMUNITY", by_community))


def verify():
    """Compare every file in expected/ to its out/ twin, line for line."""
    if not os.path.isdir(EXPECTED_DIR):
        print("FAIL: expected/ does not exist.")
        return False
    goldens = sorted(n for n in os.listdir(EXPECTED_DIR) if n.endswith(".csv"))
    if not goldens:
        print("FAIL: expected/ holds no golden files to compare against.")
        return False

    ok = True
    for name in goldens:
        exp_path = os.path.join(EXPECTED_DIR, name)
        out_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(out_path):
            print("FAIL: out/{} is missing. Run: python run.py".format(name))
            ok = False
            continue
        with open(exp_path, "r", encoding="utf-8", newline="") as f:
            expected = f.read().splitlines()
        with open(out_path, "r", encoding="utf-8", newline="") as f:
            actual = f.read().splitlines()
        if actual == expected:
            print("PASS: {} matches expected/ ({} rows).".format(
                name, max(len(actual) - 1, 0)))
            continue
        ok = False
        print("FAIL: {} differs from expected/.".format(name))
        print("  expected {} lines, got {} lines.".format(len(expected), len(actual)))
        shown = 0
        for i in range(max(len(actual), len(expected))):
            a = actual[i] if i < len(actual) else "<missing>"
            e = expected[i] if i < len(expected) else "<missing>"
            if a != e:
                print("  line {}:".format(i + 1))
                print("    expected: {}".format(e))
                print("    actual:   {}".format(a))
                shown += 1
                if shown >= 5:
                    print("  ... (further differences suppressed)")
                    break
    return ok


def print_table(columns, rows):
    """Render an aligned ASCII table. Plain ASCII prints cleanly on any console,
    including the default Windows code page. Numeric columns are right-aligned."""
    cells = [["" if v is None else str(v) for v in row] for row in rows]

    def is_number(text):
        if text == "":
            return True
        try:
            float(text)
            return True
        except ValueError:
            return False

    numeric = [all(is_number(row[i]) for row in cells) for i in range(len(columns))]
    widths = [len(columns[i]) for i in range(len(columns))]
    for row in cells:
        for i, text in enumerate(row):
            widths[i] = max(widths[i], len(text))

    def line(values):
        parts = []
        for i, text in enumerate(values):
            parts.append(text.rjust(widths[i]) if numeric[i] else text.ljust(widths[i]))
        return "  ".join(parts)

    print(line(columns))
    print("  ".join("-" * w for w in widths))
    for row in cells:
        print(line(row))


def _show_file(path, title):
    rows = _read_csv(path)
    if not rows:
        print(title + ": (no rows)")
        return
    columns = list(rows[0].keys())
    print(title)
    print("")
    print_table(columns, [[r[c] for c in columns] for r in rows])
    print("")


def show():
    """Print the results as aligned tables. Read-only: these are display-only
    projections of columns the SQL already produced."""
    yt = YEAR_TYPE_OUT if os.path.exists(YEAR_TYPE_OUT) else os.path.join(EXPECTED_DIR, "permits_by_year_worktype.csv")
    dr = DISTRICT_OUT if os.path.exists(DISTRICT_OUT) else os.path.join(EXPECTED_DIR, "district_units_running_total.csv")
    if not os.path.exists(yt):
        print("Nothing to show yet. Run: python run.py")
        return
    _show_file(yt, "Permit activity and declared value by issue year and work type:")
    if os.path.exists(dr):
        _show_file(dr, "Net new residential units by district, with running total over years:")


def main():
    args = sys.argv[1:]
    if args and args[0] == "verify":
        sys.exit(0 if verify() else 1)
    if args and args[0] == "show":
        show()
        sys.exit(0)
    if args:
        print("unknown argument: {}. Use no argument, 'verify', or 'show'.".format(args[0]))
        sys.exit(2)
    run_pipeline()
    sys.exit(0 if verify() else 1)


if __name__ == "__main__":
    main()
