"""Thin driver for the Invest NS deal book.

Every analytical rule lives in sql/. This file only sequences the SQL, copies
the BI mart into bi/exports/, re-emits the dashboard cube as a JavaScript
literal, and diffs out/ against the golden copies in expected/.

  python run.py            run the SQL end to end, then verify
  python run.py verify     golden diff only
  python run.py show       print contributions by sector as an aligned table
"""

import csv
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]

OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")
DEAL_BOOK_CSV = os.path.join(OUT_DIR, "deal_book.csv")
MART_CSV = os.path.join(OUT_DIR, "mart_deal_book.csv")
DASH_CSV = os.path.join(OUT_DIR, "dash_deal_book.csv")
BI_MART_CSV = os.path.join(HERE, "bi", "exports", "mart_deal_book.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")

DASH_TEXT_FIELDS = ["fiscal_year", "nsbi_sector", "nsbi_county", "deal_type"]
DASH_NUMBER_FIELDS = ["fiscal_year_start", "county_is_geographic", "deals",
                      "funded_deals", "blank_deals", "zero_deals",
                      "mappable_deals", "in_bounds_deals", "contribution"]


def run_pipeline():
    import duckdb

    os.chdir(HERE)  # the SQL files use paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)
    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            with open(os.path.join(HERE, "sql", name), "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
    finally:
        con.close()

    os.makedirs(os.path.dirname(BI_MART_CSV), exist_ok=True)
    shutil.copyfile(MART_CSV, BI_MART_CSV)
    print("copied mart to bi/exports/mart_deal_book.csv")

    write_data_js()
    print("regenerated dashboard/data.js")
    print("")


def write_data_js():
    """Plumbing only: re-emit out/dash_deal_book.csv as a JS array literal.

    Text fields go through json.dumps so quotes and ampersands survive.
    Numbers are copied as their CSV text, so no float rounding happens here.
    """
    with open(DASH_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    lines = []
    for r in rows:
        parts = ['"%s": %s' % (k, json.dumps(r[k])) for k in DASH_TEXT_FIELDS]
        parts += ['"%s": %s' % (k, r[k]) for k in DASH_NUMBER_FIELDS]
        lines.append("  {" + ", ".join(parts) + "}")
    header = (
        "// Generated by run.py from out/dash_deal_book.csv. Do not edit.\n"
        "// One row per fiscal year, sector, county, and deal type.\n"
        "// Money is Canadian dollars; contribution excludes blank values.\n"
    )
    body = "const DATA = [\n" + ",\n".join(lines) + "\n];\n"
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + body)


def verify():
    names = sorted(n for n in os.listdir(EXPECTED_DIR) if n.endswith(".csv"))
    if not names:
        print("FAIL: expected/ holds no golden files to compare against")
        return 1
    for name in names:
        got_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(got_path):
            print("FAIL: out/%s is missing (run: python run.py)" % name)
            return 1
        with open(os.path.join(EXPECTED_DIR, name), "r", encoding="utf-8") as f:
            want = f.read().splitlines()
        with open(got_path, "r", encoding="utf-8") as f:
            got = f.read().splitlines()
        for i in range(max(len(want), len(got))):
            w = want[i] if i < len(want) else "<missing line>"
            g = got[i] if i < len(got) else "<extra line>"
            if w != g:
                print("FAIL: %s line %d" % (name, i + 1))
                print("  expected: " + w)
                print("  got:      " + g)
                return 1
    print("PASS: %d file(s) match expected/ row for row" % len(names))
    return 0


def show():
    if not os.path.exists(DEAL_BOOK_CSV):
        print("out/deal_book.csv not found; run `python run.py` first")
        return 1
    with open(DEAL_BOOK_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    header = ["rank", "sector", "deals", "contribution", "share_pct"]
    table = [header]
    for r in rows:
        if r["section"] == "by_sector":
            table.append([
                r["rank"],
                r["nsbi_sector"],
                "{:,}".format(int(r["deals"])),
                "{:,.2f}".format(float(r["amount"])),
                r["share_pct"],
            ])

    widths = [max(len(row[i]) for row in table) for i in range(len(header))]

    def line(cells):
        out = []
        for i, cell in enumerate(cells):
            out.append(cell.ljust(widths[i]) if i == 1 else cell.rjust(widths[i]))
        return "  ".join(out)

    print("")
    print("Invest NS financial contribution by sector, 2018-2019 to 2023-2024")
    print("")
    print(line(header))
    print("  ".join("-" * w for w in widths))
    for row in table[1:]:
        print(line(row))
    print("")
    return 0


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "run"
    if mode == "run":
        run_pipeline()
        sys.exit(verify())
    if mode == "verify":
        sys.exit(verify())
    if mode == "show":
        sys.exit(show())
    print("usage: python run.py [verify|show]")
    sys.exit(2)


if __name__ == "__main__":
    main()
