// Generated by build_index.py from data/materia.json. Do not edit by hand.
window.FF7_DATA = {
  "meta": {
    "game": "Final Fantasy VII (1997, PlayStation)",
    "subject": "The materia system",
    "names": "Spell and ability names use the original North American PlayStation translation (Fire/Fire2/Fire3, Bolt, Demi, Cure, and so on).",
    "about": "A curated dataset of FF7 materia. Each materia lists its category, element, the abilities it grants, where it is first found, and how the support materia link with others. The indexer turns these fields into a graph of nodes and edges."
  },
  "categories": [
    {
      "id": "magic",
      "name": "Magic",
      "color": "Green",
      "blurb": "Casts spells, from Fire to Ultima."
    },
    {
      "id": "summon",
      "name": "Summon",
      "color": "Red",
      "blurb": "Calls a creature for one large attack."
    },
    {
      "id": "support",
      "name": "Support",
      "color": "Blue",
      "blurb": "Changes the materia placed in a linked slot next to it."
    },
    {
      "id": "command",
      "name": "Command",
      "color": "Yellow",
      "blurb": "Adds a new battle command such as Steal or Sense."
    },
    {
      "id": "independent",
      "name": "Independent",
      "color": "Purple",
      "blurb": "A passive bonus to stats or the field."
    }
  ],
  "elements": [
    "Fire",
    "Ice",
    "Lightning",
    "Earth",
    "Poison",
    "Gravity",
    "Water",
    "Wind",
    "Holy"
  ],
  "materia": [
    {
      "id": "fire",
      "name": "Fire",
      "category": "magic",
      "elements": [
        "Fire"
      ],
      "abilities": [
        "Fire",
        "Fire2",
        "Fire3"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "The basic Fire spell line. Raises Magic, lowers HP and Strength slightly."
    },
    {
      "id": "ice",
      "name": "Ice",
      "category": "magic",
      "elements": [
        "Ice"
      ],
      "abilities": [
        "Ice",
        "Ice2",
        "Ice3"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "The Ice spell line."
    },
    {
      "id": "lightning",
      "name": "Lightning",
      "category": "magic",
      "elements": [
        "Lightning"
      ],
      "abilities": [
        "Bolt",
        "Bolt2",
        "Bolt3"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Casts the Bolt spells."
    },
    {
      "id": "earth",
      "name": "Earth",
      "category": "magic",
      "elements": [
        "Earth"
      ],
      "abilities": [
        "Quake",
        "Quake2",
        "Quake3"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Quake misses flying enemies."
    },
    {
      "id": "poison",
      "name": "Poison",
      "category": "magic",
      "elements": [
        "Poison"
      ],
      "abilities": [
        "Bio",
        "Bio2",
        "Bio3"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Bio also inflicts the Poison status."
    },
    {
      "id": "gravity",
      "name": "Gravity",
      "category": "magic",
      "elements": [
        "Gravity"
      ],
      "abilities": [
        "Demi",
        "Demi2",
        "Demi3"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Demi cuts a fraction of current HP, so it ignores defense."
    },
    {
      "id": "restore",
      "name": "Restore",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Cure",
        "Cure2",
        "Regen",
        "Cure3"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "The main healing line. Pairs naturally with All."
    },
    {
      "id": "heal",
      "name": "Heal",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Poisona",
        "Esuna",
        "Resist"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Removes status ailments."
    },
    {
      "id": "revive",
      "name": "Revive",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Life",
        "Life2"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Life revives a KO'd character."
    },
    {
      "id": "seal",
      "name": "Seal",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Sleepel",
        "Silence"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Sleep and Silence status spells."
    },
    {
      "id": "mystify",
      "name": "Mystify",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Confu",
        "Berserk"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Confusion and Berserk status spells."
    },
    {
      "id": "time",
      "name": "Time",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Haste",
        "Slow",
        "Stop"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Speeds allies or slows and stops enemies."
    },
    {
      "id": "transform",
      "name": "Transform",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Mini",
        "Toad"
      ],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Shrinks an enemy or turns it into a frog."
    },
    {
      "id": "barrier",
      "name": "Barrier",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Barrier",
        "MBarrier",
        "Reflect",
        "Wall"
      ],
      "found_at": [
        "Rocket Town"
      ],
      "notes": "Barrier halves physical damage, MBarrier halves magic damage."
    },
    {
      "id": "destruct",
      "name": "Destruct",
      "category": "magic",
      "elements": [],
      "abilities": [
        "DeBarrier",
        "DeSpell",
        "Death"
      ],
      "found_at": [
        "Shinra Mansion"
      ],
      "notes": "Strips barriers and can instantly kill weak enemies."
    },
    {
      "id": "exit",
      "name": "Exit",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Exit"
      ],
      "found_at": [
        "Rocket Town"
      ],
      "notes": "Escapes from the current battle."
    },
    {
      "id": "comet",
      "name": "Comet",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Comet",
        "Comet2"
      ],
      "found_at": [
        "Forgotten Capital"
      ],
      "notes": "Non-elemental damage. Comet2 hits several times, which is why it loves Quadra Magic."
    },
    {
      "id": "contain",
      "name": "Contain",
      "category": "magic",
      "elements": [
        "Ice",
        "Wind"
      ],
      "abilities": [
        "Freeze",
        "Break",
        "Tornado",
        "Flare"
      ],
      "found_at": [
        "Mideel"
      ],
      "notes": "High tier spells, each with a chance to inflict a status."
    },
    {
      "id": "full-cure",
      "name": "Full Cure",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Full Cure"
      ],
      "found_at": [
        "Cosmo Canyon"
      ],
      "notes": "Restores a target to full HP."
    },
    {
      "id": "shield",
      "name": "Shield",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Shield"
      ],
      "found_at": [
        "Northern Cave"
      ],
      "notes": "Blocks all physical and magical damage for a few turns."
    },
    {
      "id": "ultima",
      "name": "Ultima",
      "category": "magic",
      "elements": [],
      "abilities": [
        "Ultima"
      ],
      "found_at": [
        "Mt. Corel"
      ],
      "notes": "The strongest single Magic spell, non-elemental and hits all enemies."
    },
    {
      "id": "master-magic",
      "name": "Master Magic",
      "category": "magic",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Kalm Traveler"
      ],
      "notes": "One materia that grants every Magic spell in the game."
    },
    {
      "id": "choco-mog",
      "name": "Choco/Mog",
      "category": "summon",
      "elements": [],
      "abilities": [
        "Deathblow!?"
      ],
      "found_at": [
        "Chocobo Farm"
      ],
      "notes": "The first summon you can get. Can stop an enemy."
    },
    {
      "id": "shiva",
      "name": "Shiva",
      "category": "summon",
      "elements": [
        "Ice"
      ],
      "abilities": [
        "Diamond Dust"
      ],
      "found_at": [
        "Junon"
      ],
      "notes": "Reward from Priscilla in Lower Junon."
    },
    {
      "id": "ifrit",
      "name": "Ifrit",
      "category": "summon",
      "elements": [
        "Fire"
      ],
      "abilities": [
        "Hellfire"
      ],
      "found_at": [
        "Cargo Ship"
      ],
      "notes": "Dropped after the Jenova-BIRTH fight."
    },
    {
      "id": "ramuh",
      "name": "Ramuh",
      "category": "summon",
      "elements": [
        "Lightning"
      ],
      "abilities": [
        "Judgement Bolt"
      ],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Found near the Corel Prison chocobo races."
    },
    {
      "id": "titan",
      "name": "Titan",
      "category": "summon",
      "elements": [
        "Earth"
      ],
      "abilities": [
        "Anger of the Land"
      ],
      "found_at": [
        "Gongaga"
      ],
      "notes": "Inside the ruined Gongaga reactor."
    },
    {
      "id": "odin",
      "name": "Odin",
      "category": "summon",
      "elements": [],
      "abilities": [
        "Steel Bladed Sword",
        "Gunge Lance"
      ],
      "found_at": [
        "Shinra Mansion"
      ],
      "notes": "Steel Bladed Sword can instantly kill; Gunge Lance hits enemies immune to death."
    },
    {
      "id": "leviathan",
      "name": "Leviathan",
      "category": "summon",
      "elements": [
        "Water"
      ],
      "abilities": [
        "Tidal Wave"
      ],
      "found_at": [
        "Wutai"
      ],
      "notes": "Reward for clearing the Wutai story."
    },
    {
      "id": "bahamut",
      "name": "Bahamut",
      "category": "summon",
      "elements": [],
      "abilities": [
        "Mega Flare"
      ],
      "found_at": [
        "Temple of the Ancients"
      ],
      "notes": "Dropped after the Red Dragon battle."
    },
    {
      "id": "kjata",
      "name": "Kjata",
      "category": "summon",
      "elements": [
        "Lightning",
        "Ice",
        "Fire"
      ],
      "abilities": [
        "Tetra Disaster"
      ],
      "found_at": [
        "Sleeping Forest"
      ],
      "notes": "Carries three elements at once."
    },
    {
      "id": "alexander",
      "name": "Alexander",
      "category": "summon",
      "elements": [
        "Holy"
      ],
      "abilities": [
        "Judgement"
      ],
      "found_at": [
        "Great Glacier"
      ],
      "notes": "The only easy source of Holy element damage."
    },
    {
      "id": "phoenix",
      "name": "Phoenix",
      "category": "summon",
      "elements": [
        "Fire"
      ],
      "abilities": [
        "Phoenix Flame"
      ],
      "found_at": [
        "Fort Condor"
      ],
      "notes": "Revives all KO'd party members as it attacks, which makes it strong with Final Attack."
    },
    {
      "id": "neo-bahamut",
      "name": "Neo Bahamut",
      "category": "summon",
      "elements": [],
      "abilities": [
        "Giga Flare"
      ],
      "found_at": [
        "Whirlwind Maze"
      ],
      "notes": "The second Bahamut, stronger than the first."
    },
    {
      "id": "hades",
      "name": "Hades",
      "category": "summon",
      "elements": [],
      "abilities": [
        "Black Cauldron"
      ],
      "found_at": [
        "Sunken Gelnika"
      ],
      "notes": "Inflicts a long list of status effects at once."
    },
    {
      "id": "typoon",
      "name": "Typoon",
      "category": "summon",
      "elements": [
        "Lightning",
        "Fire",
        "Ice",
        "Earth"
      ],
      "abilities": [
        "Disintegration"
      ],
      "found_at": [
        "Ancient Forest"
      ],
      "notes": "Grows stronger as it is used more."
    },
    {
      "id": "bahamut-zero",
      "name": "Bahamut ZERO",
      "category": "summon",
      "elements": [],
      "abilities": [
        "Tera Flare"
      ],
      "found_at": [
        "Cosmo Canyon"
      ],
      "notes": "The third Bahamut, formed once every Huge Materia is collected."
    },
    {
      "id": "knights-of-the-round",
      "name": "Knights of the Round",
      "category": "summon",
      "elements": [],
      "abilities": [
        "Ultimate End"
      ],
      "found_at": [
        "Round Island"
      ],
      "notes": "Thirteen separate hits. The strongest summon, hidden behind gold chocobo breeding."
    },
    {
      "id": "master-summon",
      "name": "Master Summon",
      "category": "summon",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Kalm Traveler"
      ],
      "notes": "One materia that grants every summon."
    },
    {
      "id": "all",
      "name": "All",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Item Shops"
      ],
      "notes": "Makes the linked Magic spell hit every target."
    },
    {
      "id": "elemental",
      "name": "Elemental",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Shinra Building"
      ],
      "notes": "In a weapon, adds the linked element to attacks. In armor, reduces or absorbs that element."
    },
    {
      "id": "added-effect",
      "name": "Added Effect",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Cave of the Gi"
      ],
      "notes": "In a weapon, attacks inflict the linked status. In armor, you become immune to it."
    },
    {
      "id": "added-cut",
      "name": "Added Cut",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Great Glacier"
      ],
      "notes": "Adds a normal physical hit after the linked materia is used."
    },
    {
      "id": "quadra-magic",
      "name": "Quadra Magic",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Materia Caves"
      ],
      "notes": "Casts the linked Magic four times for one turn."
    },
    {
      "id": "mp-turbo",
      "name": "MP Turbo",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Whirlwind Maze"
      ],
      "notes": "Raises the linked spell's power at a higher MP cost."
    },
    {
      "id": "sneak-attack",
      "name": "Sneak Attack",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Chance to fire the linked materia before the enemy can act."
    },
    {
      "id": "final-attack",
      "name": "Final Attack",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Triggers the linked materia the moment the character is KO'd."
    },
    {
      "id": "hp-absorb",
      "name": "HP Absorb",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Wutai"
      ],
      "notes": "Heals HP based on the damage the linked materia deals."
    },
    {
      "id": "mp-absorb",
      "name": "MP Absorb",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Wutai"
      ],
      "notes": "Refills MP based on the damage the linked materia deals."
    },
    {
      "id": "magic-counter",
      "name": "Magic Counter",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Northern Cave"
      ],
      "notes": "Counters an incoming hit by casting the linked Magic."
    },
    {
      "id": "counter",
      "name": "Counter",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Northern Cave"
      ],
      "notes": "Counters an incoming hit with the linked Command."
    },
    {
      "id": "steal-as-well",
      "name": "Steal as Well",
      "category": "support",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Wutai"
      ],
      "notes": "Steals at the same time the linked materia is used."
    },
    {
      "id": "steal",
      "name": "Steal",
      "category": "command",
      "elements": [],
      "abilities": [
        "Steal",
        "Mug"
      ],
      "found_at": [
        "Midgar Sewers"
      ],
      "notes": "Mug steals and attacks in one action."
    },
    {
      "id": "sense",
      "name": "Sense",
      "category": "command",
      "elements": [],
      "abilities": [
        "Sense"
      ],
      "found_at": [
        "Sector 6"
      ],
      "notes": "Reads an enemy's HP and weaknesses."
    },
    {
      "id": "deathblow",
      "name": "Deathblow",
      "category": "command",
      "elements": [],
      "abilities": [
        "D.Blow"
      ],
      "found_at": [
        "Gongaga"
      ],
      "notes": "A single attack that always lands a critical hit or misses entirely."
    },
    {
      "id": "manipulate",
      "name": "Manipulate",
      "category": "command",
      "elements": [],
      "abilities": [
        "Manip."
      ],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Take control of an enemy's actions."
    },
    {
      "id": "mime",
      "name": "Mime",
      "category": "command",
      "elements": [],
      "abilities": [
        "Mime"
      ],
      "found_at": [
        "Materia Caves"
      ],
      "notes": "Repeats the previous action for free, including a summon."
    },
    {
      "id": "morph",
      "name": "Morph",
      "category": "command",
      "elements": [],
      "abilities": [
        "Morph"
      ],
      "found_at": [
        "Temple of the Ancients"
      ],
      "notes": "Turns a weakened enemy into an item."
    },
    {
      "id": "throw",
      "name": "Throw",
      "category": "command",
      "elements": [],
      "abilities": [
        "Throw"
      ],
      "found_at": [
        "Wutai"
      ],
      "notes": "Throw a weapon or item at an enemy for damage."
    },
    {
      "id": "double-cut",
      "name": "Double Cut",
      "category": "command",
      "elements": [],
      "abilities": [
        "2x-Cut",
        "4x-Cut"
      ],
      "found_at": [
        "Sunken Gelnika"
      ],
      "notes": "Attack two, then four times in one turn."
    },
    {
      "id": "slash-all",
      "name": "Slash-All",
      "category": "command",
      "elements": [],
      "abilities": [
        "Slash-All",
        "Flash"
      ],
      "found_at": [
        "Ancient Forest"
      ],
      "notes": "One physical attack that hits every enemy."
    },
    {
      "id": "enemy-skill",
      "name": "Enemy Skill",
      "category": "command",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Shinra Building"
      ],
      "notes": "Learns enemy attacks and casts them as spells. Four exist in the game."
    },
    {
      "id": "w-item",
      "name": "W-Item",
      "category": "command",
      "elements": [],
      "abilities": [
        "W-Item"
      ],
      "found_at": [
        "Midgar Raid"
      ],
      "notes": "Use two items in one turn."
    },
    {
      "id": "w-magic",
      "name": "W-Magic",
      "category": "command",
      "elements": [],
      "abilities": [
        "W-Magic"
      ],
      "found_at": [
        "Northern Cave"
      ],
      "notes": "Cast two Magic spells in one turn."
    },
    {
      "id": "w-summon",
      "name": "W-Summon",
      "category": "command",
      "elements": [],
      "abilities": [
        "W-Summon"
      ],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Call two summons in one turn."
    },
    {
      "id": "master-command",
      "name": "Master Command",
      "category": "command",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Kalm Traveler"
      ],
      "notes": "One materia that grants every command."
    },
    {
      "id": "hp-plus",
      "name": "HP Plus",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Junon"
      ],
      "notes": "Raises maximum HP by up to 50 percent."
    },
    {
      "id": "mp-plus",
      "name": "MP Plus",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Cosmo Canyon"
      ],
      "notes": "Raises maximum MP by up to 50 percent."
    },
    {
      "id": "magic-plus",
      "name": "Magic Plus",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Forgotten Capital"
      ],
      "notes": "Raises the Magic stat, so spells hit harder."
    },
    {
      "id": "luck-plus",
      "name": "Luck Plus",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Temple of the Ancients"
      ],
      "notes": "Raises Luck, which raises critical hit rate."
    },
    {
      "id": "speed-plus",
      "name": "Speed Plus",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Fills the time bar faster."
    },
    {
      "id": "counter-attack",
      "name": "Counter Attack",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Mt. Nibel"
      ],
      "notes": "Counters an incoming hit with a plain physical attack. Dropped by the Materia Keeper."
    },
    {
      "id": "cover",
      "name": "Cover",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Sector 5 Slums"
      ],
      "notes": "Steps in to take hits aimed at a weakened ally."
    },
    {
      "id": "long-range",
      "name": "Long Range",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Mythril Mine"
      ],
      "notes": "Attack from the back row without the damage penalty."
    },
    {
      "id": "mega-all",
      "name": "Mega All",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Northern Cave"
      ],
      "notes": "Makes several actions hit all targets without needing All."
    },
    {
      "id": "pre-emptive",
      "name": "Pre-Emptive",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Raises the chance of a pre-emptive strike."
    },
    {
      "id": "enemy-lure",
      "name": "Enemy Lure",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Raises the random encounter rate."
    },
    {
      "id": "enemy-away",
      "name": "Enemy Away",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Lowers the random encounter rate."
    },
    {
      "id": "chocobo-lure",
      "name": "Chocobo Lure",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Chocobo Farm"
      ],
      "notes": "Needed to find chocobos in the field for breeding."
    },
    {
      "id": "exp-plus",
      "name": "Exp Plus",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Increases experience earned from battles."
    },
    {
      "id": "gil-plus",
      "name": "Gil Plus",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Gold Saucer"
      ],
      "notes": "Increases gil earned from battles."
    },
    {
      "id": "hp-mp",
      "name": "HP<->MP",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Materia Caves"
      ],
      "notes": "Swaps the character's HP and MP totals."
    },
    {
      "id": "underwater",
      "name": "Underwater",
      "category": "independent",
      "elements": [],
      "abilities": [],
      "found_at": [
        "Kalm Traveler"
      ],
      "notes": "Removes the time limit on the underwater Emerald Weapon fight."
    }
  ],
  "combos": [
    {
      "support": "all",
      "target": "restore",
      "slot": "weapon or armor",
      "effect": "Heal the whole party with one cast of Cure."
    },
    {
      "support": "all",
      "target": "fire",
      "slot": "weapon or armor",
      "effect": "Hit every enemy with a single Fire cast."
    },
    {
      "support": "elemental",
      "target": "fire",
      "slot": "weapon",
      "effect": "Adds Fire damage to physical attacks. In armor it cuts or absorbs Fire damage instead."
    },
    {
      "support": "elemental",
      "target": "ifrit",
      "slot": "armor",
      "effect": "Borrows Ifrit's Fire element to halve or absorb Fire damage."
    },
    {
      "support": "added-effect",
      "target": "odin",
      "slot": "weapon",
      "effect": "Physical attacks gain Odin's chance to instantly kill."
    },
    {
      "support": "added-effect",
      "target": "hades",
      "slot": "armor",
      "effect": "Grants immunity to the many status effects Hades inflicts."
    },
    {
      "support": "added-effect",
      "target": "seal",
      "slot": "armor",
      "effect": "Immunity to Sleep and Silence."
    },
    {
      "support": "quadra-magic",
      "target": "comet",
      "slot": "weapon or armor",
      "effect": "Casts Comet2 four times in one turn."
    },
    {
      "support": "quadra-magic",
      "target": "ultima",
      "slot": "weapon or armor",
      "effect": "Four Ultima casts from a single turn."
    },
    {
      "support": "mp-turbo",
      "target": "comet",
      "slot": "weapon or armor",
      "effect": "More Comet damage in exchange for more MP."
    },
    {
      "support": "sneak-attack",
      "target": "deathblow",
      "slot": "weapon or armor",
      "effect": "Open the battle with a Deathblow before enemies act."
    },
    {
      "support": "final-attack",
      "target": "revive",
      "slot": "weapon or armor",
      "effect": "Auto-casts Life on the character the moment they are KO'd."
    },
    {
      "support": "final-attack",
      "target": "phoenix",
      "slot": "weapon or armor",
      "effect": "On death, summons Phoenix to revive the party and burn enemies."
    },
    {
      "support": "hp-absorb",
      "target": "knights-of-the-round",
      "slot": "weapon or armor",
      "effect": "Drain the huge Knights of the Round damage back as HP."
    },
    {
      "support": "mp-absorb",
      "target": "bahamut-zero",
      "slot": "weapon or armor",
      "effect": "Refill MP from Bahamut ZERO's damage."
    },
    {
      "support": "magic-counter",
      "target": "comet",
      "slot": "weapon or armor",
      "effect": "Counter an incoming hit by auto-casting Comet."
    },
    {
      "support": "counter",
      "target": "steal",
      "slot": "weapon or armor",
      "effect": "Counter an attacker by stealing from them."
    },
    {
      "support": "steal-as-well",
      "target": "deathblow",
      "slot": "weapon or armor",
      "effect": "Steal at the same moment you land a Deathblow."
    },
    {
      "support": "added-cut",
      "target": "comet",
      "slot": "weapon or armor",
      "effect": "Add a normal physical hit after casting Comet."
    }
  ]
};
