// Generated by run.py from the SQL outputs in out/. Do not edit.
// META: the pull-date constant and the latest full year.
// BY_YEAR: one row per year, collision count, factor counts and shares.
// MONTH_HOUR: one row per hour of day, twelve month columns of counts.
const META = {"latest_full_year": 2025, "pull_date": "2026-07-09"};
const BY_YEAR = [
  {"year": 2018, "collisions": 6085, "pedestrian": 193, "bicycle": 59, "impaired": 158, "distracted": 767, "intersection": 2586, "fatal": 19, "pct_pedestrian": 3.2, "pct_bicycle": 1.0, "pct_impaired": 2.6, "pct_distracted": 12.6, "pct_intersection": 42.5, "pct_fatal": 0.3},
  {"year": 2019, "collisions": 6266, "pedestrian": 169, "bicycle": 82, "impaired": 196, "distracted": 771, "intersection": 2638, "fatal": 18, "pct_pedestrian": 2.7, "pct_bicycle": 1.3, "pct_impaired": 3.1, "pct_distracted": 12.3, "pct_intersection": 42.1, "pct_fatal": 0.3},
  {"year": 2020, "collisions": 4569, "pedestrian": 122, "bicycle": 48, "impaired": 168, "distracted": 567, "intersection": 2010, "fatal": 7, "pct_pedestrian": 2.7, "pct_bicycle": 1.1, "pct_impaired": 3.7, "pct_distracted": 12.4, "pct_intersection": 44.0, "pct_fatal": 0.2},
  {"year": 2021, "collisions": 5061, "pedestrian": 155, "bicycle": 63, "impaired": 188, "distracted": 580, "intersection": 2228, "fatal": 15, "pct_pedestrian": 3.1, "pct_bicycle": 1.2, "pct_impaired": 3.7, "pct_distracted": 11.5, "pct_intersection": 44.0, "pct_fatal": 0.3},
  {"year": 2022, "collisions": 5114, "pedestrian": 171, "bicycle": 75, "impaired": 191, "distracted": 522, "intersection": 2184, "fatal": 11, "pct_pedestrian": 3.3, "pct_bicycle": 1.5, "pct_impaired": 3.7, "pct_distracted": 10.2, "pct_intersection": 42.7, "pct_fatal": 0.2},
  {"year": 2023, "collisions": 5342, "pedestrian": 168, "bicycle": 62, "impaired": 178, "distracted": 628, "intersection": 2321, "fatal": 8, "pct_pedestrian": 3.1, "pct_bicycle": 1.2, "pct_impaired": 3.3, "pct_distracted": 11.8, "pct_intersection": 43.4, "pct_fatal": 0.1},
  {"year": 2024, "collisions": 6103, "pedestrian": 190, "bicycle": 87, "impaired": 172, "distracted": 598, "intersection": 2498, "fatal": 13, "pct_pedestrian": 3.1, "pct_bicycle": 1.4, "pct_impaired": 2.8, "pct_distracted": 9.8, "pct_intersection": 40.9, "pct_fatal": 0.2},
  {"year": 2025, "collisions": 5734, "pedestrian": 169, "bicycle": 101, "impaired": 162, "distracted": 516, "intersection": 2512, "fatal": 18, "pct_pedestrian": 2.9, "pct_bicycle": 1.8, "pct_impaired": 2.8, "pct_distracted": 9.0, "pct_intersection": 43.8, "pct_fatal": 0.3},
  {"year": 2026, "collisions": 1974, "pedestrian": 47, "bicycle": 7, "impaired": 71, "distracted": 176, "intersection": 802, "fatal": 1, "pct_pedestrian": 2.4, "pct_bicycle": 0.4, "pct_impaired": 3.6, "pct_distracted": 8.9, "pct_intersection": 40.6, "pct_fatal": 0.1}
];
const MONTH_HOUR = [
  {"hour": 0, "m01": 43, "m02": 51, "m03": 46, "m04": 30, "m05": 26, "m06": 40, "m07": 45, "m08": 51, "m09": 39, "m10": 35, "m11": 44, "m12": 41},
  {"hour": 1, "m01": 29, "m02": 32, "m03": 44, "m04": 24, "m05": 26, "m06": 41, "m07": 42, "m08": 29, "m09": 29, "m10": 39, "m11": 38, "m12": 39},
  {"hour": 2, "m01": 28, "m02": 32, "m03": 20, "m04": 27, "m05": 19, "m06": 31, "m07": 19, "m08": 26, "m09": 26, "m10": 36, "m11": 27, "m12": 35},
  {"hour": 3, "m01": 25, "m02": 31, "m03": 28, "m04": 17, "m05": 16, "m06": 21, "m07": 19, "m08": 20, "m09": 12, "m10": 15, "m11": 20, "m12": 38},
  {"hour": 4, "m01": 21, "m02": 28, "m03": 20, "m04": 21, "m05": 16, "m06": 18, "m07": 28, "m08": 18, "m09": 17, "m10": 19, "m11": 25, "m12": 31},
  {"hour": 5, "m01": 32, "m02": 43, "m03": 25, "m04": 29, "m05": 26, "m06": 32, "m07": 38, "m08": 28, "m09": 28, "m10": 35, "m11": 35, "m12": 25},
  {"hour": 6, "m01": 149, "m02": 97, "m03": 85, "m04": 86, "m05": 80, "m06": 59, "m07": 62, "m08": 71, "m09": 96, "m10": 134, "m11": 95, "m12": 92},
  {"hour": 7, "m01": 243, "m02": 219, "m03": 198, "m04": 152, "m05": 133, "m06": 135, "m07": 125, "m08": 108, "m09": 178, "m10": 208, "m11": 203, "m12": 202},
  {"hour": 8, "m01": 321, "m02": 330, "m03": 275, "m04": 192, "m05": 185, "m06": 187, "m07": 165, "m08": 182, "m09": 247, "m10": 275, "m11": 287, "m12": 260},
  {"hour": 9, "m01": 267, "m02": 223, "m03": 204, "m04": 150, "m05": 162, "m06": 142, "m07": 149, "m08": 150, "m09": 192, "m10": 200, "m11": 215, "m12": 221},
  {"hour": 10, "m01": 211, "m02": 233, "m03": 207, "m04": 166, "m05": 180, "m06": 175, "m07": 161, "m08": 155, "m09": 158, "m10": 164, "m11": 189, "m12": 224},
  {"hour": 11, "m01": 276, "m02": 231, "m03": 242, "m04": 164, "m05": 185, "m06": 221, "m07": 212, "m08": 190, "m09": 206, "m10": 212, "m11": 221, "m12": 245},
  {"hour": 12, "m01": 324, "m02": 254, "m03": 275, "m04": 198, "m05": 215, "m06": 249, "m07": 245, "m08": 254, "m09": 254, "m10": 272, "m11": 269, "m12": 307},
  {"hour": 13, "m01": 278, "m02": 234, "m03": 246, "m04": 211, "m05": 215, "m06": 235, "m07": 245, "m08": 261, "m09": 227, "m10": 246, "m11": 247, "m12": 304},
  {"hour": 14, "m01": 339, "m02": 286, "m03": 246, "m04": 218, "m05": 257, "m06": 265, "m07": 252, "m08": 233, "m09": 237, "m10": 267, "m11": 266, "m12": 292},
  {"hour": 15, "m01": 402, "m02": 328, "m03": 326, "m04": 278, "m05": 319, "m06": 323, "m07": 291, "m08": 311, "m09": 316, "m10": 357, "m11": 324, "m12": 353},
  {"hour": 16, "m01": 406, "m02": 342, "m03": 346, "m04": 311, "m05": 368, "m06": 337, "m07": 351, "m08": 320, "m09": 320, "m10": 404, "m11": 357, "m12": 370},
  {"hour": 17, "m01": 409, "m02": 271, "m03": 274, "m04": 238, "m05": 317, "m06": 291, "m07": 299, "m08": 303, "m09": 275, "m10": 318, "m11": 465, "m12": 442},
  {"hour": 18, "m01": 280, "m02": 225, "m03": 221, "m04": 183, "m05": 198, "m06": 209, "m07": 201, "m08": 160, "m09": 181, "m10": 241, "m11": 329, "m12": 285},
  {"hour": 19, "m01": 199, "m02": 206, "m03": 162, "m04": 123, "m05": 132, "m06": 144, "m07": 161, "m08": 139, "m09": 139, "m10": 239, "m11": 200, "m12": 223},
  {"hour": 20, "m01": 182, "m02": 138, "m03": 126, "m04": 119, "m05": 104, "m06": 105, "m07": 116, "m08": 121, "m09": 161, "m10": 137, "m11": 140, "m12": 155},
  {"hour": 21, "m01": 124, "m02": 126, "m03": 109, "m04": 118, "m05": 97, "m06": 112, "m07": 111, "m08": 123, "m09": 116, "m10": 107, "m11": 107, "m12": 162},
  {"hour": 22, "m01": 91, "m02": 92, "m03": 89, "m04": 72, "m05": 83, "m06": 97, "m07": 91, "m08": 81, "m09": 85, "m10": 99, "m11": 78, "m12": 116},
  {"hour": 23, "m01": 66, "m02": 56, "m03": 61, "m04": 45, "m05": 67, "m06": 66, "m07": 69, "m08": 63, "m09": 50, "m10": 61, "m11": 76, "m12": 65}
];
