"""Thin driver for the rooftop solar adoption pipeline.

All analytical logic lives in sql/. This file only executes the SQL files in
order, moves the exports where they belong, regenerates dashboard/data.js from
the mart, and diffs the output against the golden copy in expected/.

  python run.py            run the pipeline, then verify against expected/
  python run.py verify     golden diff only
  python run.py show       print the adoption summary as an aligned table
"""

import csv
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

SQL_FILES = [
    "00_schema.sql",
    "01_load.sql",
    "02_transform.sql",
    "03_analysis.sql",
    "99_export.sql",
]

OUT_DIR = os.path.join(HERE, "out")
EXPECTED_DIR = os.path.join(HERE, "expected")
SUMMARY_CSV = os.path.join(OUT_DIR, "solar_adoption.csv")
MART_CSV = os.path.join(OUT_DIR, "mart_solar.csv")
BI_MART_CSV = os.path.join(HERE, "bi", "exports", "mart_solar.csv")
DATA_JS = os.path.join(HERE, "dashboard", "data.js")


def run_pipeline():
    import duckdb

    os.chdir(HERE)  # SQL files use paths relative to this folder
    os.makedirs(OUT_DIR, exist_ok=True)
    con = duckdb.connect()
    try:
        for name in SQL_FILES:
            path = os.path.join(HERE, "sql", name)
            with open(path, "r", encoding="utf-8") as f:
                con.execute(f.read())
            print("ran sql/" + name)
        print("")
        for (line,) in con.execute(
                "SELECT line FROM headline ORDER BY ord").fetchall():
            print(line)
        print("")
    finally:
        con.close()

    os.makedirs(os.path.dirname(BI_MART_CSV), exist_ok=True)
    shutil.copyfile(MART_CSV, BI_MART_CSV)
    print("copied mart to bi/exports/mart_solar.csv")

    write_data_js()
    print("regenerated dashboard/data.js")


def write_data_js():
    """Plumbing only: re-emit the mart rows as a JS array literal."""
    with open(MART_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    lines = []
    for r in rows:
        lines.append(
            '  {"fsa": "%s", "year": %s, "installs": %s, "installed_kw": %s}'
            % (r["fsa"], r["year"], r["installs"], r["installed_kw"])
        )
    body = "const DATA = [\n" + ",\n".join(lines) + "\n];\n"
    header = (
        "// Generated by run.py from bi/exports/mart_solar.csv. Do not edit.\n"
        "// One row per FSA and year: installs and installed kW.\n"
    )
    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + body)


def verify():
    failures = 0
    checked = 0
    for name in sorted(os.listdir(EXPECTED_DIR)):
        exp_path = os.path.join(EXPECTED_DIR, name)
        got_path = os.path.join(OUT_DIR, name)
        if not os.path.exists(got_path):
            print("FAIL: out/%s is missing (run: python run.py)" % name)
            return 1
        with open(exp_path, "r", encoding="utf-8") as f:
            exp = f.read().splitlines()
        with open(got_path, "r", encoding="utf-8") as f:
            got = f.read().splitlines()
        checked += 1
        for i in range(max(len(exp), len(got))):
            e = exp[i] if i < len(exp) else "<missing line>"
            g = got[i] if i < len(got) else "<missing line>"
            if e != g:
                print("FAIL: %s line %d" % (name, i + 1))
                print("  expected: " + e)
                print("  got:      " + g)
                failures += 1
                break
    if checked == 0:
        print("FAIL: expected/ holds no golden files to compare against")
        return 1
    if failures == 0:
        print("PASS: %d file(s) match expected/ row for row" % checked)
        return 0
    return 1


def show():
    if not os.path.exists(SUMMARY_CSV):
        run_pipeline()
    with open(SUMMARY_CSV, "r", encoding="utf-8", newline="") as f:
        rows = list(csv.reader(f))
    if not rows:
        print("out/solar_adoption.csv is empty")
        return 1
    header, data = rows[0], rows[1:]
    widths = [len(h) for h in header]
    for r in data:
        for i, cell in enumerate(r):
            widths[i] = max(widths[i], len(cell))

    def fmt_line(cells):
        parts = []
        for i, cell in enumerate(cells):
            if i == 0:
                parts.append(cell.ljust(widths[i]))
            else:
                parts.append(cell.rjust(widths[i]))
        return "  ".join(parts)

    print("Nova Scotia rooftop solar adoption, provincial summary by year")
    print()
    print(fmt_line(header))
    print(fmt_line(["-" * w for w in widths]))
    for r in data:
        print(fmt_line(r))
    return 0


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "run"
    if mode == "verify":
        sys.exit(verify())
    if mode == "show":
        sys.exit(show())
    if mode == "run":
        run_pipeline()
        sys.exit(verify())
    print("usage: python run.py [verify|show]")
    sys.exit(2)


if __name__ == "__main__":
    main()
