// Generated by run.py from the exported aggregates in out/. Do not edit.
// The dashboard re-derives its headline figures from these rows; the
// derived totals must equal expected/summary.csv (see spec.md).
const DATA = {
  "summary": {
    "total_trees": "78896",
    "identified_trees": "74133",
    "unidentified_trees": "4763",
    "distinct_species": "250",
    "top_species": "Norway Maple",
    "top_species_count": "10276",
    "top_species_share_pct": "13.02",
    "most_common_dbh_class": "Class 1-2",
    "trees_with_install_year": "9997",
    "install_year_earliest": "2013",
    "install_year_latest": "2025"
  },
  "species": [
    {
      "rank": 1,
      "common": "Norway Maple",
      "scientific": "Acer platanoides",
      "count": 10276,
      "share": 13.02
    },
    {
      "rank": 2,
      "common": "Red Maple",
      "scientific": "Acer rubrum",
      "count": 7563,
      "share": 9.59
    },
    {
      "rank": 3,
      "common": "American Elm",
      "scientific": "Ulmus americana",
      "count": 4094,
      "share": 5.19
    },
    {
      "rank": 4,
      "common": "Northern Red Oak",
      "scientific": "Quercus rubra",
      "count": 3282,
      "share": 4.16
    },
    {
      "rank": 5,
      "common": "Japanese Tree Lilac",
      "scientific": "Syringa reticulata",
      "count": 3276,
      "share": 4.15
    },
    {
      "rank": 6,
      "common": "Sugar Maple",
      "scientific": "Acer saccharum",
      "count": 2432,
      "share": 3.08
    },
    {
      "rank": 7,
      "common": "Linden",
      "scientific": "Tilia (genus)",
      "count": 2096,
      "share": 2.66
    },
    {
      "rank": 8,
      "common": "Littleleaf Linden",
      "scientific": "Tilia cordata",
      "count": 1994,
      "share": 2.53
    },
    {
      "rank": 9,
      "common": "Green Ash",
      "scientific": "Fraxinus pennsylvanica",
      "count": 1921,
      "share": 2.43
    },
    {
      "rank": 10,
      "common": "Freeman Maple",
      "scientific": "Acer freemanii",
      "count": 1810,
      "share": 2.29
    },
    {
      "rank": 11,
      "common": "American Basswood",
      "scientific": "Tilia americana",
      "count": 1751,
      "share": 2.22
    },
    {
      "rank": 12,
      "common": "Northern Hackberry",
      "scientific": "Celtis occidentalis",
      "count": 1586,
      "share": 2.01
    },
    {
      "rank": 13,
      "common": "Callery Pear",
      "scientific": "Pyrus calleryana",
      "count": 1573,
      "share": 1.99
    },
    {
      "rank": 14,
      "common": "Maple",
      "scientific": "Acer (genus)",
      "count": 1565,
      "share": 1.98
    },
    {
      "rank": 15,
      "common": "White Spruce",
      "scientific": "Picea glauca",
      "count": 1519,
      "share": 1.93
    },
    {
      "rank": 16,
      "common": "Ginkgo",
      "scientific": "Ginkgo biloba",
      "count": 1153,
      "share": 1.46
    },
    {
      "rank": 17,
      "common": "Paper Birch",
      "scientific": "Betula papyrifera",
      "count": 959,
      "share": 1.22
    },
    {
      "rank": 18,
      "common": "Apple",
      "scientific": "Malus (genus)",
      "count": 899,
      "share": 1.14
    },
    {
      "rank": 19,
      "common": "Red Pine",
      "scientific": "Pinus resinosa",
      "count": 835,
      "share": 1.06
    },
    {
      "rank": 20,
      "common": "Honeylocust",
      "scientific": "Gleditisia triacanthos",
      "count": 794,
      "share": 1.01
    },
    {
      "rank": 21,
      "common": "Accolade Elm",
      "scientific": "Ulmus accolade",
      "count": 769,
      "share": 0.97
    },
    {
      "rank": 22,
      "common": "Pin Oak",
      "scientific": "Quercus palustris",
      "count": 757,
      "share": 0.96
    },
    {
      "rank": 23,
      "common": "Eastern White Pine",
      "scientific": "Pinus strobus",
      "count": 754,
      "share": 0.96
    },
    {
      "rank": 24,
      "common": "Silver Maple",
      "scientific": "Acer saccharinum",
      "count": 734,
      "share": 0.93
    },
    {
      "rank": 25,
      "common": "Northern White Cedar",
      "scientific": "Thuja occidentalis",
      "count": 725,
      "share": 0.92
    },
    {
      "rank": 26,
      "common": "Serviceberry",
      "scientific": "Amelanchier (genus)",
      "count": 691,
      "share": 0.88
    },
    {
      "rank": 27,
      "common": "Bur Oak",
      "scientific": "Quercus macrocarpa",
      "count": 649,
      "share": 0.82
    },
    {
      "rank": 28,
      "common": "London Planetree",
      "scientific": "Platanus hybrida",
      "count": 580,
      "share": 0.74
    },
    {
      "rank": 29,
      "common": "White Ash",
      "scientific": "Fraxinus americana",
      "count": 553,
      "share": 0.7
    },
    {
      "rank": 30,
      "common": "European Beech",
      "scientific": "Fagus sylvatica",
      "count": 523,
      "share": 0.66
    },
    {
      "rank": 31,
      "common": "Blue Spruce",
      "scientific": "Picea pungens",
      "count": 500,
      "share": 0.63
    },
    {
      "rank": 32,
      "common": "Elm",
      "scientific": "Elm (genus)",
      "count": 476,
      "share": 0.6
    },
    {
      "rank": 33,
      "common": "Common Lilac",
      "scientific": "Syringa vulgaris",
      "count": 473,
      "share": 0.6
    },
    {
      "rank": 34,
      "common": "Tulip Tree",
      "scientific": "Liriodendron tulipifera",
      "count": 457,
      "share": 0.58
    },
    {
      "rank": 35,
      "common": "English Oak",
      "scientific": "Quercus robur",
      "count": 454,
      "share": 0.58
    },
    {
      "rank": 36,
      "common": "Oak",
      "scientific": "Quercus (genus)",
      "count": 404,
      "share": 0.51
    },
    {
      "rank": 37,
      "common": "Spruce",
      "scientific": "Picea (genus)",
      "count": 398,
      "share": 0.5
    },
    {
      "rank": 38,
      "common": "European Mountain Ash",
      "scientific": "Sorbus aucuparia",
      "count": 390,
      "share": 0.49
    },
    {
      "rank": 39,
      "common": "Red Spruce",
      "scientific": "Picea rubens",
      "count": 389,
      "share": 0.49
    },
    {
      "rank": 40,
      "common": "Sweetgum",
      "scientific": "Liguidambar styraciflua",
      "count": 376,
      "share": 0.48
    },
    {
      "rank": 41,
      "common": "Scotch Pine",
      "scientific": "Pinus sylvestris",
      "count": 359,
      "share": 0.46
    },
    {
      "rank": 42,
      "common": "Black Walnut",
      "scientific": "Juglans nigra",
      "count": 350,
      "share": 0.44
    },
    {
      "rank": 43,
      "common": "Burning Bush",
      "scientific": "Euonymus alatus",
      "count": 313,
      "share": 0.4
    },
    {
      "rank": 44,
      "common": "Quaking Aspen",
      "scientific": "Populus tremuloides",
      "count": 309,
      "share": 0.39
    },
    {
      "rank": 45,
      "common": "Amur Maple",
      "scientific": "Acer ginnala",
      "count": 291,
      "share": 0.37
    },
    {
      "rank": 46,
      "common": "Austrian Pine",
      "scientific": "Pinus nigra",
      "count": 281,
      "share": 0.36
    },
    {
      "rank": 47,
      "common": "Swamp White Oak",
      "scientific": "Quercus bicolor",
      "count": 274,
      "share": 0.35
    },
    {
      "rank": 48,
      "common": "Kentucky Coffeetree",
      "scientific": "Gymnocladus dioicus",
      "count": 271,
      "share": 0.34
    },
    {
      "rank": 49,
      "common": "Silver Linden",
      "scientific": "Tilia tomentosa",
      "count": 255,
      "share": 0.32
    },
    {
      "rank": 50,
      "common": "Yellow Birch",
      "scientific": "Betula alleghaniensis",
      "count": 250,
      "share": 0.32
    },
    {
      "rank": 51,
      "common": "River Birch",
      "scientific": "Betula nigra",
      "count": 248,
      "share": 0.31
    },
    {
      "rank": 52,
      "common": "Japanese Maple",
      "scientific": "Acer palmatum",
      "count": 245,
      "share": 0.31
    },
    {
      "rank": 53,
      "common": "Amur Corktree",
      "scientific": "Phellodendron amurense",
      "count": 239,
      "share": 0.3
    },
    {
      "rank": 54,
      "common": "Gray Birch",
      "scientific": "Betula populifolia",
      "count": 233,
      "share": 0.3
    },
    {
      "rank": 55,
      "common": "Eastern Hophornbeam",
      "scientific": "Ostrya virginiana",
      "count": 228,
      "share": 0.29
    },
    {
      "rank": 56,
      "common": "Hedge Maple",
      "scientific": "Acer campestre",
      "count": 224,
      "share": 0.28
    },
    {
      "rank": 57,
      "common": "Sour Cherry",
      "scientific": "Prunus cerasus",
      "count": 209,
      "share": 0.26
    },
    {
      "rank": 58,
      "common": "Japanese Zelkova",
      "scientific": "Zelkova serrata",
      "count": 195,
      "share": 0.25
    },
    {
      "rank": 59,
      "common": "Black Locust",
      "scientific": "Robinia pseudoacacia",
      "count": 186,
      "share": 0.24
    },
    {
      "rank": 60,
      "common": "Norway Spruce",
      "scientific": "Picea abies",
      "count": 181,
      "share": 0.23
    },
    {
      "rank": 61,
      "common": "Birch",
      "scientific": "Betula (genus)",
      "count": 180,
      "share": 0.23
    },
    {
      "rank": 62,
      "common": "Pine",
      "scientific": "Pinus (genus)",
      "count": 180,
      "share": 0.23
    },
    {
      "rank": 63,
      "common": "Ash",
      "scientific": "Fraxinus (genus)",
      "count": 179,
      "share": 0.23
    },
    {
      "rank": 64,
      "common": "Eastern Red Cedar",
      "scientific": "Juniperus virginiana",
      "count": 176,
      "share": 0.22
    },
    {
      "rank": 65,
      "common": "Horsechestnut",
      "scientific": "Aesculus hippocastanum",
      "count": 176,
      "share": 0.22
    },
    {
      "rank": 66,
      "common": "White Mulberry",
      "scientific": "Morus alba",
      "count": 172,
      "share": 0.22
    },
    {
      "rank": 67,
      "common": "Wych elm",
      "scientific": "Ulmus glabra",
      "count": 152,
      "share": 0.19
    },
    {
      "rank": 68,
      "common": "White Oak",
      "scientific": "Quercus alba",
      "count": 145,
      "share": 0.18
    },
    {
      "rank": 69,
      "common": "Northern Catalpa",
      "scientific": "Catalpa speciosa",
      "count": 141,
      "share": 0.18
    },
    {
      "rank": 70,
      "common": "Bigtooth Aspen",
      "scientific": "Populus grandidentata",
      "count": 136,
      "share": 0.17
    },
    {
      "rank": 71,
      "common": "Sycamore Maple",
      "scientific": "Acer pseudoplatanus",
      "count": 130,
      "share": 0.16
    },
    {
      "rank": 72,
      "common": "Mountain Maple",
      "scientific": "Acer spicatum",
      "count": 121,
      "share": 0.15
    },
    {
      "rank": 73,
      "common": "Paperbark Maple",
      "scientific": "Acer griseum",
      "count": 118,
      "share": 0.15
    },
    {
      "rank": 74,
      "common": "Zelkova",
      "scientific": "Zelkova (genus)",
      "count": 118,
      "share": 0.15
    },
    {
      "rank": 75,
      "common": "Common Chokecherry",
      "scientific": "Prunus virginiana",
      "count": 116,
      "share": 0.15
    },
    {
      "rank": 76,
      "common": "American Sycamore",
      "scientific": "Platanus occidentalis",
      "count": 112,
      "share": 0.14
    },
    {
      "rank": 77,
      "common": "Turkish Hazelnut",
      "scientific": "Corylus colurna",
      "count": 110,
      "share": 0.14
    },
    {
      "rank": 78,
      "common": "Magnolia",
      "scientific": "Magnolia (genus)",
      "count": 109,
      "share": 0.14
    },
    {
      "rank": 79,
      "common": "Eastern Hemlock",
      "scientific": "Tsuga canadensis",
      "count": 104,
      "share": 0.13
    },
    {
      "rank": 80,
      "common": "Balsam Fir",
      "scientific": "Abies balsamea",
      "count": 101,
      "share": 0.13
    },
    {
      "rank": 81,
      "common": "Common Pear",
      "scientific": "Pyrus communis",
      "count": 101,
      "share": 0.13
    },
    {
      "rank": 82,
      "common": "American Beech",
      "scientific": "Fagus grandifolia",
      "count": 94,
      "share": 0.12
    },
    {
      "rank": 83,
      "common": "Pin Cherry",
      "scientific": "Prunus pensylvanica",
      "count": 91,
      "share": 0.12
    },
    {
      "rank": 84,
      "common": "Dwarf Mountain Pine",
      "scientific": "Pinus mugo",
      "count": 87,
      "share": 0.11
    },
    {
      "rank": 85,
      "common": "Hawthorn",
      "scientific": "Crataegus (genus)",
      "count": 87,
      "share": 0.11
    },
    {
      "rank": 86,
      "common": "Green Hawthorn",
      "scientific": "Crataegus viridis",
      "count": 86,
      "share": 0.11
    },
    {
      "rank": 87,
      "common": "White Poplar",
      "scientific": "Populus alba",
      "count": 86,
      "share": 0.11
    },
    {
      "rank": 88,
      "common": "European Hornbeam",
      "scientific": "Carpinus betulus",
      "count": 85,
      "share": 0.11
    },
    {
      "rank": 89,
      "common": "Willow",
      "scientific": "Salix (genus)",
      "count": 85,
      "share": 0.11
    },
    {
      "rank": 90,
      "common": "Silver Birch",
      "scientific": "Betula pendula",
      "count": 82,
      "share": 0.1
    },
    {
      "rank": 91,
      "common": "Bigleaf Linden",
      "scientific": "Tilia platyphyllos",
      "count": 81,
      "share": 0.1
    },
    {
      "rank": 92,
      "common": "Black Tupelo",
      "scientific": "Nyssa sylvatica",
      "count": 81,
      "share": 0.1
    },
    {
      "rank": 93,
      "common": "European Ash",
      "scientific": "Fraxinus excelsior",
      "count": 81,
      "share": 0.1
    },
    {
      "rank": 94,
      "common": "Eastern Redbud",
      "scientific": "Cercis canadensis",
      "count": 80,
      "share": 0.1
    },
    {
      "rank": 95,
      "common": "Ussurian Pear",
      "scientific": "Pyrus ussuriensis",
      "count": 78,
      "share": 0.1
    },
    {
      "rank": 96,
      "common": "Yew",
      "scientific": "Taxus (genus)",
      "count": 78,
      "share": 0.1
    },
    {
      "rank": 97,
      "common": "Katsura Tree",
      "scientific": "Cercidiphyllum japonicum",
      "count": 73,
      "share": 0.09
    },
    {
      "rank": 98,
      "common": "European Linden",
      "scientific": "Tilia europaea",
      "count": 69,
      "share": 0.09
    },
    {
      "rank": 99,
      "common": "Panicle Hydrangea",
      "scientific": "Hydrangea paniculata",
      "count": 67,
      "share": 0.08
    },
    {
      "rank": 100,
      "common": "Ohio Buckeye",
      "scientific": "Aesculus glabra",
      "count": 66,
      "share": 0.08
    },
    {
      "rank": 101,
      "common": "Black Poplar",
      "scientific": "Populus nigra",
      "count": 65,
      "share": 0.08
    },
    {
      "rank": 102,
      "common": "Staghorn Sumac",
      "scientific": "Rhus hirta",
      "count": 63,
      "share": 0.08
    },
    {
      "rank": 103,
      "common": "Sawara False Cypress",
      "scientific": "Chamaecyparis pisifera",
      "count": 61,
      "share": 0.08
    },
    {
      "rank": 104,
      "common": "American Hornbeam",
      "scientific": "Carpinus caroliniana",
      "count": 58,
      "share": 0.07
    },
    {
      "rank": 105,
      "common": "Black Oak",
      "scientific": "Quercus velutina",
      "count": 57,
      "share": 0.07
    },
    {
      "rank": 106,
      "common": "Kwanzan Cherry",
      "scientific": "Prunus serrulata",
      "count": 57,
      "share": 0.07
    },
    {
      "rank": 107,
      "common": "Kousa Dogwood",
      "scientific": "Cornus kousa",
      "count": 55,
      "share": 0.07
    },
    {
      "rank": 108,
      "common": "Red Horsechestnut",
      "scientific": "Aesculus x carnea",
      "count": 54,
      "share": 0.07
    },
    {
      "rank": 109,
      "common": "Dawn Redwood",
      "scientific": "Metasequoia glyptostroboides",
      "count": 51,
      "share": 0.06
    },
    {
      "rank": 110,
      "common": "Tamarack",
      "scientific": "Larix laricina",
      "count": 48,
      "share": 0.06
    },
    {
      "rank": 111,
      "common": "Balsam Poplar",
      "scientific": "Populus balsamifera",
      "count": 47,
      "share": 0.06
    },
    {
      "rank": 112,
      "common": "Weeping Willow",
      "scientific": "Salix x sepulcralis",
      "count": 47,
      "share": 0.06
    },
    {
      "rank": 113,
      "common": "Scarlet Oak",
      "scientific": "Quercus coccinea",
      "count": 43,
      "share": 0.05
    },
    {
      "rank": 114,
      "common": "Black Spruce",
      "scientific": "Picea mariana",
      "count": 42,
      "share": 0.05
    },
    {
      "rank": 115,
      "common": "Atlantic White Cedar",
      "scientific": "Chamaecyparis thyoides",
      "count": 40,
      "share": 0.05
    },
    {
      "rank": 116,
      "common": "Beech",
      "scientific": "Fagus (genus)",
      "count": 37,
      "share": 0.05
    },
    {
      "rank": 117,
      "common": "Rocky Mountain Maple",
      "scientific": "Acer glabrum",
      "count": 37,
      "share": 0.05
    },
    {
      "rank": 118,
      "common": "Plum",
      "scientific": "Prunus (genus)",
      "count": 36,
      "share": 0.05
    },
    {
      "rank": 119,
      "common": "Smoketree",
      "scientific": "Cotinus coggygria",
      "count": 36,
      "share": 0.05
    },
    {
      "rank": 120,
      "common": "Boxelder",
      "scientific": "Acer negundo",
      "count": 34,
      "share": 0.04
    },
    {
      "rank": 121,
      "common": "Forsythia",
      "scientific": "Forsythia (genus)",
      "count": 33,
      "share": 0.04
    },
    {
      "rank": 122,
      "common": "English Elm",
      "scientific": "Ulmus procera",
      "count": 31,
      "share": 0.04
    },
    {
      "rank": 123,
      "common": "Black Cherry",
      "scientific": "Prunus serotina",
      "count": 30,
      "share": 0.04
    },
    {
      "rank": 124,
      "common": "Purpleleaf Sand Cherry",
      "scientific": "Prunus x cistena",
      "count": 30,
      "share": 0.04
    },
    {
      "rank": 125,
      "common": "Chinquapin oak",
      "scientific": "Quercis muehlenbergii",
      "count": 29,
      "share": 0.04
    },
    {
      "rank": 126,
      "common": "Flowering Dogwood",
      "scientific": "Cornus florida",
      "count": 29,
      "share": 0.04
    },
    {
      "rank": 127,
      "common": "Siberian Elm",
      "scientific": "Ulmus pumila",
      "count": 29,
      "share": 0.04
    },
    {
      "rank": 128,
      "common": "Northern Pin Oak",
      "scientific": "Quercus ellipsoidalis",
      "count": 28,
      "share": 0.04
    },
    {
      "rank": 129,
      "common": "Bigtooth Maple",
      "scientific": "Acer grandidentatum",
      "count": 27,
      "share": 0.03
    },
    {
      "rank": 130,
      "common": "Butternut",
      "scientific": "Juglans cinerea",
      "count": 27,
      "share": 0.03
    },
    {
      "rank": 131,
      "common": "Russian Olive",
      "scientific": "Elaeagnus angustifolia",
      "count": 26,
      "share": 0.03
    },
    {
      "rank": 132,
      "common": "Witch Hazel",
      "scientific": "Hamamelis virginiana",
      "count": 26,
      "share": 0.03
    },
    {
      "rank": 133,
      "common": "Alder Buckthorn",
      "scientific": "Frangula alnus",
      "count": 24,
      "share": 0.03
    },
    {
      "rank": 134,
      "common": "Japanese Persimmon",
      "scientific": "Diospyros virginiana",
      "count": 24,
      "share": 0.03
    },
    {
      "rank": 135,
      "common": "Downy Serviceberry",
      "scientific": "Amelanchier arborea",
      "count": 23,
      "share": 0.03
    },
    {
      "rank": 136,
      "common": "Eastern Cottonwood",
      "scientific": "Populus deltoides",
      "count": 23,
      "share": 0.03
    },
    {
      "rank": 137,
      "common": "Nootka Cypress",
      "scientific": "Chamaecyparis nootkatensis",
      "count": 22,
      "share": 0.03
    },
    {
      "rank": 138,
      "common": "Shingle Oak",
      "scientific": "Quercus imbricaria",
      "count": 21,
      "share": 0.03
    },
    {
      "rank": 139,
      "common": "Dogwood",
      "scientific": "Cornus (genus)",
      "count": 20,
      "share": 0.03
    },
    {
      "rank": 140,
      "common": "Striped Maple",
      "scientific": "Acer pensylvanicum",
      "count": 20,
      "share": 0.03
    },
    {
      "rank": 141,
      "common": "Common Ninebark",
      "scientific": "Physocarpus opulifolius",
      "count": 19,
      "share": 0.02
    },
    {
      "rank": 142,
      "common": "Fir",
      "scientific": "Abies (genus)",
      "count": 19,
      "share": 0.02
    },
    {
      "rank": 143,
      "common": "Black Birch",
      "scientific": "Betula lenta",
      "count": 18,
      "share": 0.02
    },
    {
      "rank": 144,
      "common": "Hickory",
      "scientific": "Carya (genus)",
      "count": 18,
      "share": 0.02
    },
    {
      "rank": 145,
      "common": "Overcup Oak",
      "scientific": "Quercus lyrata",
      "count": 18,
      "share": 0.02
    },
    {
      "rank": 146,
      "common": "Privet",
      "scientific": "Ligustrum (genus)",
      "count": 18,
      "share": 0.02
    },
    {
      "rank": 147,
      "common": "Leatherleaf viburnum",
      "scientific": "Viburnum rhytidophyllum",
      "count": 17,
      "share": 0.02
    },
    {
      "rank": 148,
      "common": "Eastern Serviceberry",
      "scientific": "Amelanchier canadensis",
      "count": 16,
      "share": 0.02
    },
    {
      "rank": 149,
      "common": "Spotted Oak",
      "scientific": "Quercus shumardii",
      "count": 16,
      "share": 0.02
    },
    {
      "rank": 150,
      "common": "Star Magnolia",
      "scientific": "Magnolia stellata",
      "count": 15,
      "share": 0.02
    },
    {
      "rank": 151,
      "common": "Black Ash",
      "scientific": "Fraxinus nigra",
      "count": 14,
      "share": 0.02
    },
    {
      "rank": 152,
      "common": "Jack Pine",
      "scientific": "Pinus banksiana",
      "count": 14,
      "share": 0.02
    },
    {
      "rank": 153,
      "common": "Mountain Ash",
      "scientific": "Sorbus (genus)",
      "count": 14,
      "share": 0.02
    },
    {
      "rank": 154,
      "common": "Amur Chokecherry",
      "scientific": "Prunus maackii",
      "count": 13,
      "share": 0.02
    },
    {
      "rank": 155,
      "common": "Bitternut Hickory",
      "scientific": "Carya cordiformis",
      "count": 13,
      "share": 0.02
    },
    {
      "rank": 156,
      "common": "Bristly Locust",
      "scientific": "Robinia hispida",
      "count": 13,
      "share": 0.02
    },
    {
      "rank": 157,
      "common": "European Larch",
      "scientific": "Larix decidua",
      "count": 13,
      "share": 0.02
    },
    {
      "rank": 158,
      "common": "Morden Hawthorn",
      "scientific": "Crataegus mordenensis",
      "count": 13,
      "share": 0.02
    },
    {
      "rank": 159,
      "common": "Siberian Crabapple",
      "scientific": "Malus baccata",
      "count": 13,
      "share": 0.02
    },
    {
      "rank": 160,
      "common": "White Fir",
      "scientific": "Abies concolor",
      "count": 13,
      "share": 0.02
    },
    {
      "rank": 161,
      "common": "American Mountain Ash",
      "scientific": "Sorbus americana",
      "count": 12,
      "share": 0.02
    },
    {
      "rank": 162,
      "common": "Red Alder",
      "scientific": "Alnus rubra",
      "count": 12,
      "share": 0.02
    },
    {
      "rank": 163,
      "common": "Red Osier Dogwood",
      "scientific": "Cornus sericea",
      "count": 12,
      "share": 0.02
    },
    {
      "rank": 164,
      "common": "Cedar Elm",
      "scientific": "Ulmus crassifolia",
      "count": 11,
      "share": 0.01
    },
    {
      "rank": 165,
      "common": "Corkscrew Willow",
      "scientific": "Salix matsudana",
      "count": 11,
      "share": 0.01
    },
    {
      "rank": 166,
      "common": "Oakleaf Mountain Ash",
      "scientific": "Sorbus thuringiaca",
      "count": 10,
      "share": 0.01
    },
    {
      "rank": 167,
      "common": "Saucer Magnolia",
      "scientific": "Magnolia soulangeana",
      "count": 10,
      "share": 0.01
    },
    {
      "rank": 168,
      "common": "White Hickory",
      "scientific": "Carya tomentosa",
      "count": 10,
      "share": 0.01
    },
    {
      "rank": 169,
      "common": "Chinese Elm",
      "scientific": "Ulmus parvifolia",
      "count": 9,
      "share": 0.01
    },
    {
      "rank": 170,
      "common": "Japanese Angelica",
      "scientific": "Aralia elata",
      "count": 9,
      "share": 0.01
    },
    {
      "rank": 171,
      "common": "Cedar of Lebanon",
      "scientific": "Cedrus libani",
      "count": 8,
      "share": 0.01
    },
    {
      "rank": 172,
      "common": "Holly",
      "scientific": "Ilex (genus)",
      "count": 8,
      "share": 0.01
    },
    {
      "rank": 173,
      "common": "Slippery Elm",
      "scientific": "Ulmus rubra",
      "count": 8,
      "share": 0.01
    },
    {
      "rank": 174,
      "common": "Blue Ash",
      "scientific": "Fraxinus quadrangulata",
      "count": 7,
      "share": 0.01
    },
    {
      "rank": 175,
      "common": "English Walnut",
      "scientific": "Juglans regia",
      "count": 7,
      "share": 0.01
    },
    {
      "rank": 176,
      "common": "Honeysuckle",
      "scientific": "Lonicera (genus)",
      "count": 7,
      "share": 0.01
    },
    {
      "rank": 177,
      "common": "Japanese spindle",
      "scientific": "Euonymus japonicus",
      "count": 7,
      "share": 0.01
    },
    {
      "rank": 178,
      "common": "Oregon ash",
      "scientific": "Fraxinus latifolia",
      "count": 7,
      "share": 0.01
    },
    {
      "rank": 179,
      "common": "Black Willow",
      "scientific": "Salix nigra",
      "count": 6,
      "share": 0.01
    },
    {
      "rank": 180,
      "common": "Common Hawthorn",
      "scientific": "Crataegus monogyna",
      "count": 6,
      "share": 0.01
    },
    {
      "rank": 181,
      "common": "Red Elderberry",
      "scientific": "Sambucus racemosa",
      "count": 6,
      "share": 0.01
    },
    {
      "rank": 182,
      "common": "Rhododendron",
      "scientific": "Rhododendron (genus)",
      "count": 6,
      "share": 0.01
    },
    {
      "rank": 183,
      "common": "Southern Catalpa",
      "scientific": "Catalpa bignonioides",
      "count": 6,
      "share": 0.01
    },
    {
      "rank": 184,
      "common": "Spirea",
      "scientific": "Spiraea (genus)",
      "count": 6,
      "share": 0.01
    },
    {
      "rank": 185,
      "common": "Weigela",
      "scientific": "Weigela (genus)",
      "count": 6,
      "share": 0.01
    },
    {
      "rank": 186,
      "common": "American Chestnut",
      "scientific": "Castanea dentata",
      "count": 5,
      "share": 0.01
    },
    {
      "rank": 187,
      "common": "Cucumber Tree",
      "scientific": "Magnolia acuminata",
      "count": 5,
      "share": 0.01
    },
    {
      "rank": 188,
      "common": "Poplar",
      "scientific": "Populus (genus)",
      "count": 5,
      "share": 0.01
    },
    {
      "rank": 189,
      "common": "Quince Tree",
      "scientific": "Cydonia oblonga",
      "count": 5,
      "share": 0.01
    },
    {
      "rank": 190,
      "common": "Golden Chain Tree",
      "scientific": "Laburnum x watereri",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 191,
      "common": "Guelder-rose",
      "scientific": "Viburnum opulus",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 192,
      "common": "Japanese Hornbeam",
      "scientific": "Carpinus japonica",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 193,
      "common": "Pawpaw",
      "scientific": "Asimina triloba",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 194,
      "common": "Pitch Pine",
      "scientific": "Pinus rigida",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 195,
      "common": "Siberian Peashrub",
      "scientific": "Caragana arborescens",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 196,
      "common": "Swiss Pine",
      "scientific": "Pinus cembra",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 197,
      "common": "Yellow Bird Magnolia",
      "scientific": "Magnolia x brooklynensis",
      "count": 4,
      "share": 0.01
    },
    {
      "rank": 198,
      "common": "American Holly",
      "scientific": "Ilex opaca",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 199,
      "common": "Bigleaf Maple",
      "scientific": "Acer macrophyllum",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 200,
      "common": "Devil's Walking Stick",
      "scientific": "Aralia spinosa",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 201,
      "common": "English Hawthorn",
      "scientific": "Cartaegus laevigata",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 202,
      "common": "Grand fir",
      "scientific": "Abies grandis",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 203,
      "common": "Peach",
      "scientific": "Prunus persica",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 204,
      "common": "Rose of Sharon",
      "scientific": "Hibiscus syriacus",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 205,
      "common": "Sargent Cherry",
      "scientific": "Prunus sargentii",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 206,
      "common": "Sassafras",
      "scientific": "Sassafras albidum",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 207,
      "common": "Winged Elm",
      "scientific": "Ulmus alata",
      "count": 3,
      "share": 0.0
    },
    {
      "rank": 208,
      "common": "Atlas Cedar",
      "scientific": "Cedrus atlantica",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 209,
      "common": "Beaked Hazelnut",
      "scientific": "Corylus cornuta",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 210,
      "common": "Black Hickory",
      "scientific": "Carya texana",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 211,
      "common": "Bosnian Pine",
      "scientific": "Pinus heldreichii",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 212,
      "common": "Douglas Fir",
      "scientific": "Pseudotsuga menziesii",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 213,
      "common": "Fringetree",
      "scientific": "Chionanthus virginicus",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 214,
      "common": "Goldenrain Tree",
      "scientific": "Koelreuteria paniculata",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 215,
      "common": "Gutta-percha",
      "scientific": "Palaquium gutta",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 216,
      "common": "Hinoki False Cypress",
      "scientific": "Chamaecyparis obtusa",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 217,
      "common": "Hydrangea",
      "scientific": "Hydrangea (genus)",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 218,
      "common": "Japanese Umbrella Pine",
      "scientific": "Sciadopitys verticillata",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 219,
      "common": "Japanese yew",
      "scientific": "Taxus cuspidata",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 220,
      "common": "Korean Fir",
      "scientific": "Abies koreana",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 221,
      "common": "Pagoda Dogwood",
      "scientific": "Cornus alternifolia",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 222,
      "common": "Pioneer elm",
      "scientific": "Ulmus hollandica",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 223,
      "common": "Tea Crabapple",
      "scientific": "Malus hupehensis",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 224,
      "common": "Trident Maple",
      "scientific": "Acer buergerianum",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 225,
      "common": "Yellow Catalpa",
      "scientific": "Catalpa ovata",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 226,
      "common": "Yulan Magnolia",
      "scientific": "Magnolia denudata",
      "count": 2,
      "share": 0.0
    },
    {
      "rank": 227,
      "common": "American Plum",
      "scientific": "Prunus americana",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 228,
      "common": "Amur Maackia",
      "scientific": "Maackia amurensis",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 229,
      "common": "Asian Hazelnut",
      "scientific": "Corylus heterophylla",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 230,
      "common": "Autumn Brilliance Serviceberry",
      "scientific": "Amelanchier x grandiflora",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 231,
      "common": "Giant Hazel",
      "scientific": "Corylus maxima",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 232,
      "common": "Grey Alder",
      "scientific": "Alnus incana",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 233,
      "common": "Himalayan White Birch",
      "scientific": "Betula utilis",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 234,
      "common": "Japanese Barberry",
      "scientific": "Berberis thunbergii",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 235,
      "common": "Lewis mock-orange",
      "scientific": "Philadelphus lewisii",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 236,
      "common": "Loebner Magnolia",
      "scientific": "Magnolia x loebneri",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 237,
      "common": "Loquat",
      "scientific": "Eriobotrya japonica",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 238,
      "common": "Narrowleaf meadowsweet",
      "scientific": "Spiraea alba",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 239,
      "common": "Oriental bittersweet",
      "scientific": "Celastrus orbiculatus",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 240,
      "common": "Pecan",
      "scientific": "Carya illinoinensis",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 241,
      "common": "Post Oak",
      "scientific": "Quercus stellata",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 242,
      "common": "Rock Elm",
      "scientific": "Ulmus thomasii",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 243,
      "common": "Sand Hickory",
      "scientific": "Carya pallida",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 244,
      "common": "Seven-sons tree",
      "scientific": "Heptacodium miconioides",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 245,
      "common": "Shrubby cinquefoil",
      "scientific": "Dasiphora fruticosa",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 246,
      "common": "Smoothleaf Elm",
      "scientific": "Ulmus carpinifolia",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 247,
      "common": "Tropical Ash",
      "scientific": "Fraxinus uhdei",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 248,
      "common": "Umbrella Magnolia",
      "scientific": "Magnolia tripetala",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 249,
      "common": "Washington Hawthorn",
      "scientific": "Crataegus phaenopyrum",
      "count": 1,
      "share": 0.0
    },
    {
      "rank": 250,
      "common": "Wolf Willow",
      "scientific": "Elaeagnus commutata",
      "count": 1,
      "share": 0.0
    }
  ],
  "dbh": [
    {
      "cls": "Class 1-2",
      "count": 41855,
      "share": 53.05
    },
    {
      "cls": "Class 3-4",
      "count": 25452,
      "share": 32.26
    },
    {
      "cls": "Class 5-6",
      "count": 9011,
      "share": 11.42
    },
    {
      "cls": "Class 7-9",
      "count": 2003,
      "share": 2.54
    },
    {
      "cls": "Unknown",
      "count": 575,
      "share": 0.73
    }
  ],
  "wires": [
    {
      "label": "Clear of wires",
      "count": 43803,
      "share": 55.52
    },
    {
      "label": "Under wires",
      "count": 34445,
      "share": 43.66
    },
    {
      "label": "Unknown",
      "count": 648,
      "share": 0.82
    }
  ],
  "setting": [
    {
      "label": "Street right-of-way",
      "count": 73045,
      "share": 92.58
    },
    {
      "label": "Open space",
      "count": 5851,
      "share": 7.42
    }
  ]
};
